### ISSUE TITLE
Problem with non-resolvable global npm packages

### ISSUE THREAD

**Issue by bjesuiter** [moonrepo/proto#101]
Hi there, 

I tried to install wrtc in one of my projects with:   
`pnpm add wrtc `

This fails with: 
```
✖ pnpm add wrtc   
Packages: +3
+++
Progress: resolved 385, reused 377, downloaded 0, added 0, done
node_modules/.pnpm/wrtc@0.4.7/node_modules/wrtc: Running install script, failed in 129ms
.../.pnpm/wrtc@0.4.7/node_modules/wrtc install$ node scripts/download-prebuilt.js
│ /bin/sh: node-pre-gyp: command not found
└─ Failed in 129ms at /Users/bjesuiter/Develop/bjesuiter/bgf-translation-tagungsapp/node_modules/.pnpm/wrtc@0.4.7/node_modules/wrtc
 ELIFECYCLE  Command failed with exit code 1.
```

After that, I tried to install `node-pre-gyp` with 
```
npm i -g @mapbox/node-pre-gyp
```

(since the non-scoped variant of this package is deprecated) 

=> But it still does not work. 

## Problem found 

After further inspection i found, that i have no location in my path for globally installed npm packages.  
Your Docs say here https://moonrepo.dev/docs/proto/tools#npm-pnpm-yarn: 

```
Global binaries
Installs to ~/.proto/tools/node/globals/bin.
Internally all package managers [install globals](https://moonrepo.dev/docs/proto/commands/install-global) with npm into the location above.
```

But this location does not exist on my macbook.  
I only have: 

```
.proto/tools/npm 
❯ ls
8.11.0          9.6.4           9.6.6           manifest.json
```

## Debugging 

When I try to install the package with pnpm I get: 

```
 pnpm add -g @mapbox/node-pre-gyp
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.

```

I could do this now, but I think, this should be solved by proto, otherwise this kind-of defeats it's purpose.

**Comment by bjesuiter** [comment]
## Update 

I found the command 

```
proto ig node @mapbox/node-pre-gyp
```

which creates the folder i was missing. but, shouldn't this folder also be created when I try to install this package as a global via npm or pnpm?

**Comment by milesj** [comment]
@bjesuiter Yeah, right now you have to use `proto install-global` for this to "work". We currently don't intercept the npm/pnpm/yarn commands.

The way the Node.js ecosystem handles globals is kind of trash, and is documented a bit here: https://moonrepo.dev/docs/proto/faq#how-can-i-install-a-global-binary-for-a-language

I agree this is a bit... undesirable, but I'm not sure what the best way to fix this is. The way proto works is a bit different than nvm for example.

**Comment by bjesuiter** [comment]
Ok, that makes sense. Thank you!
