### ISSUE TITLE
Support node-gyp tool

### ISSUE THREAD

**Issue by phnx47** [moonrepo/proto#102]
`npm` depends on `node-gyp`, can find binary here: `${PROTO_ROOT}/tools/npm/${version}/bin/node-gyp-bin/node-gyp`.

Can you support `node-gyp` tool?

**Comment by milesj** [comment]
@phnx47 I'm not entirely sure what this entails. Does `node-gyp` need to be available globally? Or that you want to manually install it via proto?

**Comment by phnx47** [comment]
@milesj Yes, globally like `npx`. If you install `npm` then you install `node-gyp` as well.

My case - I maintain [ledger-live](https://github.com/LedgerHQ/ledger-live) for ArchLinux AUR. LedgerHQ switched to proto, so I switched for build package too. `npm`, `pnpm`, `node` from proto, but `node-gyp` from my system. I want all node.js tools be from `proto` during build. 

```ini
node="${PROTO_ROOT}/bin/node"
pnpm="${PROTO_ROOT}/bin/pnpm"
npm="${PROTO_ROOT}/bin/npm"
node-gyp="/usr/bin/node-gyp"
```

**Comment by phnx47** [comment]
@milesj Thanks!
