### ISSUE TITLE
can't install node 14 on m1 macs

### ISSUE THREAD

**Issue by hayes** [moonrepo/proto#122]
Node does not have a `darwin-arm64` build for node 14, which causes installation to fail on m1 macs

**Comment by milesj** [comment]
@hayes Do you not receive an error or anything? What exactly is happening?

**Comment by hayes** [comment]
<img width="1092" alt="Screenshot 2023-06-05 at 10 32 11 AM" src="https://github.com/moonrepo/proto/assets/816527/739f4c8a-1599-4bfc-bda5-57ffc2a91d0f">

Looks like https://nodejs.org/dist/v14.21.3/node-v14.21.3-darwin-arm64.tar.xz is looking for the native m1 build, but I don't think node starting creating builds for m1 until node 16 (https://nodejs.org/dist/v14.21.3/)

**Comment by milesj** [comment]
Ok that's the error I expected. I can improve the message a bit for 404s.

**Comment by hayes** [comment]
@milesj does that mean you can't use proto if you want to use node 14?  Seems like it should just install the intel build for node versions before 16 right?

**Comment by hayes** [comment]
yup, it works great.  It's slightly slower because it will run through rosetta, but basically anything build for intel will run fine
