### ISSUE TITLE
Install script runs into 404 when trying to specify version

### ISSUE THREAD

**Issue by jakst** [moonrepo/proto#138]
I bumped into [this issue](https://github.com/moonrepo/proto/issues/136), so wanted to downgrade to an earlier version. I used this command `curl -fsSL https://moonrepo.dev/install/proto.sh | bash -s -- v0.10.6`, but it gives a 404.

Looking at the install script and comparing it to the URLs on the releases page, it seems like you need to change all cases of `$target` like this, i.e. remove the `$version_part` variable.

```diff
- "Darwin arm64") target="proto_cli$version_part-aarch64-apple-darwin" ;;
+ "Darwin arm64") target="proto_cli-aarch64-apple-darwin" ;;
```

**Comment by milesj** [comment]
@jakst Thanks for the report, will fix.

**Comment by milesj** [comment]
Should be fixed now.

**Comment by ackushiw** [comment]
For those trying to install a specific version of proto use the curl command without the `v`

```
curl -fsSL https://moonrepo.dev/install/proto.sh | bash -s -- 0.19.0
```
