### ISSUE TITLE
Add support for Terraform

### ISSUE THREAD

**Issue by itsezc** [moonrepo/proto#14]
The Terraform CLI is a popular tool that is installed as part of many packages, it would be great if Proto supports such tooling to be integrated so that a dev environment can have Terraform pre-installed

**Comment by RichiCoder1** [comment]
Tfenv would be good inspiration here: https://github.com/tfutils/tfenv

**Comment by milesj** [comment]
Now that we support plugins, this can be implemented there: https://moonrepo.dev/docs/proto/plugins#toml-schema-plugin
