### ISSUE TITLE
Defining the local version outside of the cwd

### ISSUE THREAD

**Issue by hayes** [moonrepo/proto#140]
It would be great to be able to explicitly define local versions of tools without having to have a config file in the local directory. 

My specific use case:

* I am the only one using proto, so I don't want to add a proto specific config file
* I need to run specific versions of tools, but can't make the engines config specific
  * eg we have node set to `>=18` and I need to run certain thing with node 18, but have 20 installed as well, which results in proto automatically using node 20

I could add the proto config file to .gitignore, but I'd rather have a way to define this via a config file stored in my home directory or something

**Comment by milesj** [comment]
@hayes 

> I need to run certain thing with node 18

Is this like all the time? Or for one-off things?

Right now, there's 2 ways around this.

1. You can set `PROTO_NODE_VERSION` env var.
2. You can set the default global version to an 18 version.

**Comment by hayes** [comment]
The env var is a good tip, I'll try that.  I don't think the global option works, because it detects the engines config and then selects the latest version matching that config (I think, it does seem to use 20, even when 18 is set as the global version)

**Comment by milesj** [comment]
I removed the `engines` check in 0.14, so this should be a bit easier to handle.

**Comment by milesj** [comment]
Gonna close this. The only other solution is using `.nvmrc` or a similar file, as proto will read those.
