### ISSUE TITLE
bug: rustup not syncing manifest

### ISSUE THREAD

**Issue by ericmccarthy7** [moonrepo/proto#142]
I ran into this working on the python PR and noticed it happens for rust too.

<img width="1271" alt="Screenshot 2023-07-03 at 10 01 27 PM" src="https://github.com/moonrepo/proto/assets/1617878/f00425d1-7cd8-4407-a8db-ce991803b7ed">

To reproduce:
- use rustup to install rust 1.70 outside of proto
- use proto to try to install rust 1.70
- it says its installed
- when I try to list installed rust versions it just lists other versions, not the one already installed

Could potentially solve by checking the manifest when calling install if something is already installed, and if so to update the manifest?

Seems like an edge case but wanted to report the bug 👍

**Comment by milesj** [comment]
Yeah, I was afraid this would crop up eventually. Proto isn't aware of anything that happens outside of it, so any `rustup` commands ran manually.

Right now proto's implementation is very strict, and commands run the same for every tool, so adding custom logic specific to Rust currently isn't possible. I think once WASM plugins land, this'll be easy to solve.

**Comment by milesj** [comment]
In proto 0.14, we now keep this in sync anytime `proto install rust` is called.
