### ISSUE TITLE
Add support for Wrangler

### ISSUE THREAD

**Issue by itsezc** [moonrepo/proto#16]
Cloudflare Wrangler is a CLI to manage deployments for your Cloudflare related products, very popular among hobbyist developers and it would be nice to see Proto provide integrations with it.

Reference:
https://developers.cloudflare.com/workers/wrangler/install-and-update/

**Comment by milesj** [comment]
Now that we support plugins, this can probably be implemented there: https://moonrepo.dev/docs/proto/plugins#toml-schema-plugin
