### ISSUE TITLE
`--pin` does not go into effect if the version is already installed

### ISSUE THREAD

**Issue by jakst** [moonrepo/proto#195]
### What version?

0.17.0

### Which command?

proto install --pin node 20.5.0

### What happened?

When running the install command with the `--pin` flag, the global default does not change if that version was already installed. I expect the pinning to go into effect regardless of whether the version was already installed or not

### Operating system?

MacOS

### Architecture?

x64

**Comment by milesj** [comment]
@jakst Interesting workflow, never thought about this. Can add it, but you can also use `proto global` for now too.

**Comment by jakst** [comment]
@milesj but `proto global node 20.5.0` doesn't install the version as well, right? What I'm looking for is to not have to use two commands for `install + switch` version, and not having to know up front whether the version is already installed or not
