### ISSUE TITLE
No possibility to check already installed tools

### ISSUE THREAD

**Issue by lkster** [moonrepo/proto#196]
### What version?

0.17.0

### What happened?

Whether it's proto bin, proto list or any other command, there's always a need to provide either id of a package or both id and version. I'd love to have some command such as just `proto list` to see what tools I have already installed.

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
Will add in the next release.

**Comment by milesj** [comment]
Added `proto tools` in v0.18.
