### ISSUE TITLE
Install older version not working on Windows

### ISSUE THREAD

**Issue by devi-000** [moonrepo/proto#198]
### What version?

0.12.1

### Which command?

proto install

### What happened?

I'm trying to install this older version (https://github.com/moonrepo/proto/releases/tag/v0.12.1) and it fails because I'm missing the required argument TOOL

### Any logs?

error: the following required arguments were not provided:
  TOOL

Usage: proto.exe install TOOL [SEMVER] [-- PASSTHROUGH...]

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
@devi-000 What commands are you running exactly to hit this error?

**Comment by devi-000** [comment]
I'm just trying to install this version from here: https://github.com/moonrepo/proto/releases/tag/v0.12.1
After downloading and extracting the files, when I try to run the `.\proto.exe install` in Windows PowerShell as Administrator, I'm getting this error: 
```
error: the following required arguments were not provided:
  <TOOL>

Usage: proto.exe install <TOOL> [SEMVER] [-- <PASSTHROUGH>...]
```

Can you please tell me the steps I should follow to install this version? 
Thanks!

**Comment by milesj** [comment]
@devi-000 The `install` command installs tools, it doesn't install proto itself, if that's what you're trying to do.

To install proto, just drag the `proto` binary to a directory that's on your `PATH`. If you already had proto installed, it's `~/.proto/bin`.
