### ISSUE TITLE
Error when running pnpm

### ISSUE THREAD

**Issue by devi-000** [moonrepo/proto#199]
### What version?

0.17.0

### Which command?

proto use

### What happened?

I'm using the latest proto version (0.17.0)
Installed necessary tools (node, npm, pnpm) using 'proto use' command.
Once I try to use pnpm I get the following errors:
![error](https://github.com/moonrepo/proto/assets/136474686/d4274a5d-a808-4cef-9ca0-12f087c9e6a8)

I tried installing different pnpm versions using 'proto install pnpm' and I got the same error.

Until today, I was using an older version of proto and I didn't encounter this issue.

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
@devi-000 What version of windows are you using? And do you have `powershell.exe` and `pwsh.exe`?

**Comment by milesj** [comment]
Can you try 0.17.1.

**Comment by devi-000** [comment]
@milesj Thanks for the fix! Now it works!
