### ISSUE TITLE
Broken state after aborting an install command

### ISSUE THREAD

**Issue by jakst** [moonrepo/proto#225]
### What version?

0.19.1

### Which command?

proto install

### What happened?

I ran `proto install pnpm 8.8.0`, and then aborted the command half way through. After that the same command would get stuck in an endless installation whenever I ran it. The only thing that resolved the issue was blowing away the `~/.proto` folder and reinstalling proto. 

After reinstalling proto I intentionally tried to break proto again with `proto install bun 1.0.3` and aborting, and managed to break it in the same way. So this seems reproducible with multiple tools.

### Operating system?

MacOS

### Architecture?

Arm64

**Comment by milesj** [comment]
I'm not really sure what the fix would be here? Maybe a `--force` option for install?

The problem I'm guessing is that the directory is locked, because it was never unlocked.

**Comment by jakst** [comment]
Can you detect the lock on the subsequent install and prompt for a force? It might be hard for many users to realize they need to use the --force flag otherwise.

**Comment by milesj** [comment]
The waiting/hanging is because if the lock. If the lock exists, the program waits until the lock is removed.

Let me think about this a bit more. Maybes theres some kind of cleanup I can trigger when receiving a signal.

**Comment by jakst** [comment]
Is it possible to install to a temporary location, and then switch in the new binary as a last step? This would reduce the time you need to have a lock enabled

**Comment by milesj** [comment]
Trying this https://github.com/moonrepo/proto/pull/226

**Comment by milesj** [comment]
Ok I think 0.19.2 should handle this

**Comment by jakst** [comment]
@milesj I think the new method has some problems. I keep getting this error message

<img width="645" alt="image" src="https://github.com/moonrepo/proto/assets/3687893/6f2752ec-73d6-4acf-b480-969c47055e89">

**Comment by milesj** [comment]
@jakst When this happens, have you checked what's at `~/.proto/tools/pnpm/8.9.0`?

**Comment by jakst** [comment]
Haven't checked the actual contents, but I tried clearing the folder and rerunning, without success. I can check

**Comment by milesj** [comment]
Yeah I'm curious what's actually there that's blocking it.

This isn't running in parallel with another process yeah?

**Comment by milesj** [comment]
Just going to delete it if it does exist: https://github.com/moonrepo/proto/pull/230

**Comment by jakst** [comment]
> Yeah I'm curious what's actually there that's blocking it.
> 
> This isn't running in parallel with another process yeah?

Sorry, I was doing other things and forgot to check, but now I by habit bumped to the fixed version before I had a chance to test it 😅 

No parallell proto process was running.
