### ISSUE TITLE
Proto misparses version emitted by corepack

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#231]
### What version?

0.19.3

### Which command?

npm

### What happened?

`corepack` suggests embedding a hash in the `package.json#packageManager` field https://github.com/nodejs/corepack/blob/2533d128872b9a42318d841718e635b29c761a96/README.md?plain=1#L68-L82 and currently writes this when you do `corepack use npm` or `corepack up`.

When running the `npm` shim, proto chokes on this format:

> Error: proto::version::unresolved
> 
>   × Failed to resolve a semantic version for
>   │ 10.2.0+sha256.c362077587b1e782e5aef3dcf85826399ae5  
>   │ 52ad66b760e2585c4ac11102243f.

Note that `npm` ignores the build metadata (anything after `+`), per https://github.com/npm/cli/issues/1479

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
Interesting, this must be new? I don't remember corepack doing this in the past. Or maybe it's just a bug.

Should be an easy fix but I'll wait to see what the node.js team has to say.

**Comment by rotu** [comment]
Definitely intentional https://github.com/nodejs/corepack/blob/0b7abb9833d332bad97902260d31652482c274a0/README.md#when-authoring-packages but relatively new. The format was introduced on purpose in https://github.com/nodejs/corepack/pull/133 but corepack only started creating these version strings in 0.20 https://github.com/nodejs/corepack/pull/291.

I'm of the opinion that it's an abuse of semver, but that this needs to be supported anyway for corepack compatibility.

**Comment by milesj** [comment]
Sounds good, easy enough to fix.

**Comment by milesj** [comment]
Fix here https://github.com/moonrepo/node-plugin/pull/10

**Comment by milesj** [comment]
Released a new plugin. You can delete the downloaded ~/.proto/plugins and try this again.
