### ISSUE TITLE
Error when running node ps1 script

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#233]
### What version?

0.19.3

### What happened?

Some scripts fail on proto in Powershell in Windows due to missing `node.exe`.

E.g. `proto run npm -- install esbuild`

```
.\node_modules\.bin\esbuild --version
&: C:\Users\dan\Source\scratch2\node_modules\.bin\esbuild.ps1:24
Line |
  24 |      & "node$exe"  "$basedir/../esbuild/bin/esbuild" $args
     |        ~~~~~~~~~~
     | The term 'node.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check
     | the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

It seems there is a node shim in `~/.proto/bin/node.cmd`, which is in my PATH. There is also a bin in  `C:\Users\dan\.proto\tools\node\20.8.0\node.exe`, which is *not* in my path.

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
I'm assuming the `node_modules` in this case were installing via npm?

**Comment by rotu** [comment]
> I'm assuming the `node_modules` in this case were installing via npm?

Yep. Here's an example from `npm` itself:
https://unpkg.com/npm@10.2.0/bin/npm.ps1

I think it would be a good idea for `proto` (and `npm`, incidentally) to generate shims which are executables *instead of* `.cmd` or `.ps1` files. Here are a few good arguments: https://github.com/npm/bin-links/issues/71.

**Comment by milesj** [comment]
Yeah my initial goal was to generate `.exe` files on the fly that would basically act like a shim, but I've been unable to get it working yet. That's definitely a future goal.

I have some changes in v0.20 that will help with this issue, but I wouldn't consider it a permanent fix, more of an alternative solution.

**Comment by rotu** [comment]
I’m not sure but I think it might also do to have a custom file extension, add it to the shell’s PATH_EXT, and register proto.exe as a handler for such files.

I don’t think a PowerShell function would work on Windows though - I think `npx` tends to use `cmd.exe` instead.

**Comment by milesj** [comment]
In v0.20, we now also create bin symlinks, which should help solve these ".exe" use cases.
