### ISSUE TITLE
Discord support link error

### ISSUE THREAD

**Issue by ImBIOS** [moonrepo/proto#235]
### What happened?

![image](https://github.com/moonrepo/proto/assets/41441643/cb6a6d35-bfe5-4c29-8bb7-908f9d4bac64)

![image](https://github.com/moonrepo/proto/assets/41441643/f19734dd-2e88-43b3-b6c4-1beb751300ec)

I wanna ask support for how to set default node version, thank you.

### Operating system?

MacOS

### Architecture?

Arm64

**Comment by ImBIOS** [comment]
Nope

**Comment by milesj** [comment]
Fixed
