### ISSUE TITLE
Hard to find docs on how to set default nodejs version

### ISSUE THREAD

**Issue by ImBIOS** [moonrepo/proto#239]
### What version?

0.19.3

### What happened?

How to set nodejs default version? Where can I found the docs?

### Operating system?

MacOS

### Architecture?

Arm64

**Comment by ImBIOS** [comment]
```
 ➜  proto pin node 18
proto commands
pin  -- Pin a default global or local version of a tool.
```

I think this one :v sorry. after a week, finally found it in the dumbest way I can imagine.

**Comment by milesj** [comment]
All the information is can be found here: https://moonrepo.dev/docs/proto/commands/pin
