### ISSUE TITLE
proto migrate v0.20 panic on windows

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#252]
### What version?

0.20.2

### Which command?

proto migrate

### What happened?

On Windows, `proto migrate v0.20` crashes when "updating shell profile".

The output is slightly misleading, since I think proto exclusively update the path with `setx`, not by updating the [PowerShell profile script](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3#profile-types-and-locations).

### Any logs?

<pre>
.\.proto\bin\proto.exe setup --shell powershell --log debug
[DEBUG 2023-10-23 12:35:22] proto  Running proto v0.20.2  args=["C:\\Users\\dan\\.proto\\bin\\proto.exe", "setup", "--shell", "powershell", "--log", "debug"]
[DEBUG 12:35:22] proto::commands::setup:setup  Updating PATH with setx command
</pre>

<pre>
proto migrate v0.20
[ INFO 2023-10-23 11:42:17] proto::commands::migrate::v0_20:migrate  Loading tools...
[ INFO 11:42:18] proto::commands::migrate::v0_20:migrate  Deleting old shims...
[ INFO 11:42:18] proto::commands::migrate::v0_20:migrate  Generating new shims...
[ INFO 11:42:18] proto::commands::migrate::v0_20:migrate  Linking new binaries...
[ INFO 11:42:18] proto::commands::migrate::v0_20:migrate  Updating shell profile...
Error:   × Main thread panicked.
  ├─▶ at crates\cli\src\commands\migrate\v0_20.rs:63:66
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
</pre>

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
I always forget about Windows 😓 

This should do it https://github.com/moonrepo/proto/pull/253

**Comment by ackushiw** [comment]
I'm getting a similar error in a Gitlab CI/CD Pipeline

```
Error:   × Main thread panicked.
  ├─▶ at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/
  │   thread/mod.rs:686:29
  ╰─▶ failed to spawn thread: Os { code: 11, kind: WouldBlock, message:
      "Resource temporarily unavailable" }
         0: 0x557c34c73fe2 - rust_begin_unwind
         1: 0x557c3436d273 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
         2: 0x557c3436d67a - core::result::unwrap_failed::hccb456d39e9c31fc
         3: 0x557c349a726a -
      proto_core::helpers::is_offline_no_cache::h0fe940672761bc32
         4: 0x557c349a7d27 - proto_core::helpers::is_offline::hd37aeadc9bf7b345
         5: 0x557c3498e384 - once_cell::imp::OnceCell<T>::initialize::
      {{closure}}::h46e8e7006ff087ce
         6: 0x557c347571cd -
      once_cell::imp::initialize_or_wait::h3d9515472a105be3
         7: 0x557c343a4ff2 -
      once_cell::imp::OnceCell<T>::initialize::h2ed9aba8fb4049ec
         8: 0x557c3476db78 - proto_core::tool_loader::load_tool::
      {{closure}}::he278257c180732be
         9: 0x557c3493c7e5 - proto::commands::run::run::{{closure}}::
      {{closure}}::h34d26e47daa16711
        10: 0x557c348770ca - <T as starbase::system::SystemFunc>::call::
      {{closure}}::hb3f42077714f70e8
        11: 0x557c34c23357 - <starbase::system::CallbackSystem as
      starbase::system::System>::run::{{closure}}::h25d7154cf0a60a43
        12: 0x557c348bc4f8 - starbase::app::App::run_systems_in_parallel::
      {{closure}}::{{closure}}::hc656cddc6183fd5f
        13: 0x557c348932f1 - tokio::runtime::task::raw::poll::h1fe6c71126eea60f
        14: 0x557c34cc0480 -
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h364
      22c09498893[50](https://gitlab.rialtic.dev/gitlab-engineering/gitlab-ui/console-ui/-/jobs/808383#L50)
        15: 0x[55](https://gitlab.rialtic.dev/gitlab-engineering/gitlab-ui/console-ui/-/jobs/808383#L55)7c34cbe7fe -
      tokio::runtime::scheduler::multi_thread::worker::run::h270df6a4db17[56](https://gitlab.rialtic.dev/gitlab-engineering/gitlab-ui/console-ui/-/jobs/808383#L56)72
        16: 0x5[57](https://gitlab.rialtic.dev/gitlab-engineering/gitlab-ui/console-ui/-/jobs/808383#L57)c34cc434e - tokio::runtime::task::raw::poll::h3e94ad39d32fff[82](https://gitlab.rialtic.dev/gitlab-engineering/gitlab-ui/console-ui/-/jobs/808383#L82)
```

**Comment by milesj** [comment]
@ackushiw That seems weird. What version of proto is that?

This error seems like proto is unable to create a system thread? Not sure why that would be the case.

**Comment by rotu** [comment]
It's called Windows because it breaks all the time :-).

I think this can be made *much* more intuitive:

- The detected shell should be shown in stderr with `proto setup --profile`. Maybe this should even be shown on stderr.
- The current behavior on Windows should probably be given a name like `proto setup --shell winreg`.

I do think `proto setup --shell powershell` should update the powershell profile script, and `proto setup` should update the powershell profile if it already exists.

I currently have the following in my profile, which works despite the [comment here](https://github.com/moonrepo/proto/blob/92c940645793862215991173dbbef419f712ee8f/crates/cli/src/commands/setup.rs#L62-L63).
```pwsh
$env:PROTO_HOME=(Join-Path $HOME ".proto")
$env:PATH=(Join-Path $env:PROTO_HOME "shims")+";"+$env:PATH
$env:PATH=(Join-Path $env:PROTO_HOME "bin")+";"+$env:PATH
```

And my execution policy is:
`Set-ExecutionPolicy -Scope CurrentUser RemoteSigned`

**Comment by ackushiw** [comment]
@milesj I think I had the CI setup for v0.19 but it get's the latest version every time it runs.

Can I install a specific version using the example in https://github.com/moonrepo/proto/issues/138?

**Comment by milesj** [comment]
@rotu I don't know anything about Windows shells/dev environments, or how they work. I'm probably not the best choice to implement this functionality. Always open to PRs.

@ackushiw Are you using the install script or the github actions? Install script should work using a version without "v", like "0.19.0".

**Comment by ackushiw** [comment]
@milesj should I open a new issue? Seems like it's unrelated to the original

**Comment by milesj** [comment]
Yeah, new issue is probably best.
