### ISSUE TITLE
Autoinstall causes tool to get reinstalled each time

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#254]
### What version?

0.20.3

### Which command?

proto run

### What happened?

I have `PROTO_AUTO_INSTALL="true"` and Node 21 was not explicitly `proto install`'ed. Every time I `proto run node` it reinstalls node 21.1.0.

When I run `proto run node` it seems to add the version to `manifest.json#installed_versions` and then remove it when the process completes. Proto does not clean up the tool itself at `$PROTO_HOME/tools/node/21.1.0`.

### Any logs?

[log.txt](https://github.com/moonrepo/proto/files/13122295/log.txt)

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
This makes sense since the install happens in a sub-process and we already have the manifest loaded in the parent process. I've been meaning to rework the manifest, so maybe this is that time.
