### ISSUE TITLE
local .prototools causes global config to be ignored

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#255]
### What version?

0.20.3

### What happened?

If there is a `.prototools` file, it seems like `auto-install` in the global `.proto/config.toml` is ignored.

I assume this is not intended, but it's [not clear from the docs](https://github.com/moonrepo/moon/blob/8f8ee9d44ba25ca89c7591af53869e9c3be3de3c/website/docs/proto/config.mdx).

It should probably also be documented how multiple `.prototools` files are expected to interact when running from a nested directory.

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
@rotu This is very surprising since they are completely separate configs (and structs in Rust), and don't interact at all with each other. If you have a reproducible example, that'll help.

**Comment by rotu** [comment]
D'oh! This was user error. I created the global config file at the incorrect path!
