### ISSUE TITLE
RFC: Tool-level configuration

### ISSUE THREAD

**Issue by milesj** [moonrepo/proto#261]
# RFC: Tool-level configuration

In its current state, proto does not support configuring a tool outside of the version string in `.prototools`. This is fine for most tools, but some tools have complex workflows that are not supported by the version string. For example, Node.js installs a bundled version of npm, which can be disabled by passing the `--no-bundled-npm` flag when installing. What if this was a configured setting instead?

There is another exception to this, the `node-intercept-globals` setting in `~/.proto/config.toml`. This is a weird one, since the `config.toml` file is meant for _user settings_, and not tool specific settings, but at the time, there was no other location for this setting to exist.

## Problem

- There's no way to configure a tool besides the version.
- There's no way for third-party tools to add settings to `~/.proto/config.toml`.
	- This file should only be for user settings also.
- There's no way for plugins to accept customizable settings.
- Installation specific arguments (`proto install tool -- --args`) are:
	- Not typed in Rust.
	- Not easily discoverable.
	- Annoying to manually provide for each install.

## Proposal

To solve the problems above, in `.prototools`, instead of configuring just a version string, you can configure an object of settings unique to that tool. For example:

```toml
node = { version = "20.0.0", bundled-npm = false, intercept-globals = false }
npm = "9.0.0"
```

These settings would then be associated with the instance of that tool, and will be accessible from the WASM plugin using a `get_tool_config` function.

This would solve the problems above by:

- Configuration is per-tool and internally would be represented as a JSON `HashMap<String, Value>`.
	- Plugins could easily access these settings.
	- Rust based WASM plugins can easily type and validate these settings.
	- Strict API contract.
- Moves tool settings out of `~/.proto/config.toml`.
	- We can move this out of the plugin layer since it shouldn't be aware of user settings, only the runtime should.
- Plugins may still support arbitrary install arguments via hooks.

**Comment by rotu** [comment]
I’m not sold on the bundled `npm`. It seems like somewhat of an edge case.

How would you add something like `typescript` or `swc` to `.prototools`? Or is the idea that it should live in `package.json`?

**Comment by milesj** [comment]
@rotu Bundled npm is already a thing in proto.

As for ts/swc, you can simply install them as a global package. `proto install-global node typescript`, or just the native `npm install --global typescript`. If you really really want it to be in proto, and configured in `.prototools`, you'd have to create a TOML/WASM plugin for it.

**Comment by rotu** [comment]
> @rotu Bundled npm is already a thing in proto.

Yes, and it's a problem if you're trying to think of `.prototools` declaratively.

For instance if I `proto install npm 9 --pin` then `proto install node 20 --pin`, I wind up with both my `npm` shim and `proto bin npm` pointing to the `npm 10`, bundled with `node`, instead of the explicitly installed one.

I think it can make sense to install `npm` when installing `node`. But I think this should be recorded on the `npm` key. E.g. it should look something like:

```
node = { version = "20.0.0", intercept-globals = false }
npm = "bundled"
```

> As for ts/swc, you can simply install them as a global package. `proto install-global node typescript`, or just the native `npm install --global typescript`. If you really really want it to be in proto, and configured in `.prototools`, you'd have to create a TOML/WASM plugin for it.

Got it. I figured "global dependencies" were subsidiary to a tool (hence why they can be added and removed interactively with `proto install-global`/`list-global`/`uninstall-global`).

Maybe consider allowing something like this down the road, so `proto use` can set up richer dev environments:

```
node = {
  version = "20.0.0"
  dependencies = ["typescript@4.9.5", "swc@1.0.11"]
}
```

**Comment by milesj** [comment]
> For instance if I proto install npm 9 --pin then proto install node 20 --pin, I wind up with both my npm shim and proto bin npm pointing to the npm 10, bundled with node, instead of the explicitly installed one.

Yeah that seems like a bug/oversight. Easy enough fix.

**Comment by rotu** [comment]
If there are options that necessitate a different binary (e.g. linking against musl vs libc), would the plugin need to disambiguate the version by tool ID and/or version? Or can the plugin resolve the tool based on the tool config?

**Comment by rotu** [comment]
> @rotu Do you have an example in mind for that? Having a hard time thinking of a use case.

- Binaries linked against musl vs libc, especially if both are present
- 32-bit vs 64-bit implementations of a binary
- Python built from source vs downloaded
- Multiple tools implementing a common standard (e.g. `pypy` and `cpython` have executables rightly named `python`)

**Comment by milesj** [comment]
Right but what about this in relation to how the settings are configured in `.prototools`? 

These all sound like scenarios that the WASM plugin itself would handle.

**Comment by rotu** [comment]
> Right but what about this in relation to how the settings are configured in `.prototools`?
> 
> These all sound like scenarios that the WASM plugin itself would handle.

Precisely. How would this change `DetectVersionOutput`, `LoadVersionsOutput`, `ResolveVersionInput`, `DownloadPrebuiltInput` (if at all)?

**Comment by milesj** [comment]
Ideally it shouldn't change the WASM functions that plugins must implement. Instead, there will be a new help function like `get_tool_config` that plugins can call whenever the need it to access the configuration, and handle their business logic accordingly.

**Comment by milesj** [comment]
Landing in next version https://github.com/moonrepo/proto/pull/318
