### ISSUE TITLE
add command to uninstall all version

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/proto#270]
### What version?

0.21.0

### Which command?

proto uninstall

### What happened?

uninstall requires to specify specific version.

```bash
proto uninstall moon 1.15.4
```

Would be good if the following was supported so all version of moon would be installed.

```bash
proto uninstall moon *
```

### Operating system?

Linux

### Architecture?

x64

**Comment by milesj** [comment]
@prabirshrestha There is but its under the clean command, `proto clean --purge node`.

**Comment by milesj** [comment]
Ok added in 0.22, just omit the version and it prompts you.
