### ISSUE TITLE
Unable to find an executable binary for yarn, expected file ~/.proto/tools/yarn/1.22.20/bin/yarn.js

### ISSUE THREAD

**Issue by bryanjswift** [moonrepo/proto#286]
### What version?

The version bundled with moon 1.11.1

### What happened?

It appears that the structure of the archive downloaded for yarn v1 changed in the just released yarn 1.22.20 such that there is a `package` folder in the `~/.proto/tools/yarn/1.22.20` directory this causes proto to be unable to find the specific tool path `~/.proto/tools/yarn/1.22.20/bin/yarn.js` (because it exists at `~/.proto/tools/yarn/1.22.20/package/bin/yarn.js`). This is specifically a problem with the node_depman plugin but I can't find the source or a repository to report the issue there. 

There also doesn't appear to be a way to tell proto to use a different version of yarn v1 when the toolchain specifies yarn 2+

I don't expect this to be limited to a specific version of proto because it has to do with how to tool version is unpacked.

### Operating system?

MacOS

### Architecture?

Arm64

**Comment by milesj** [comment]
Annoying, fix here: https://github.com/moonrepo/node-plugin/pull/20

**Comment by Robinnnnn** [comment]
appreciate this report and the quick fix @milesj, our CI started failing as well: https://github.com/gallery-so/gallery/actions/runs/6869327266/job/18681866538?pr=2083

should we expect this to be autofixed once the update is released?

**Comment by milesj** [comment]
It should for older versions of moon/proto. Latest versions use fixed versions now.

**Comment by Robinnnnn** [comment]
@milesj still seeing issues despite upgrading moon + proto, moving convo to discord: https://discord.com/channels/974160221452763146/1174101530748669952/1174101530748669952

**Comment by milesj** [comment]
https://github.com/moonrepo/node-plugin/releases/tag/v0.5.1
