### ISSUE TITLE
"auto-install" is defined as boolean, yet a string is expected

### ISSUE THREAD

**Issue by ugudango** [moonrepo/proto#292]
### What version?

0.23.0

### Which command?

proto run deno

### What happened?

I configured the `.prototools` files as follows:

```toml
auto-install = true
deno = "1.38.2"
```

The command fails. The logs can be found down below.

This is the relevant file

https://github.com/moonrepo/proto/blob/04c7f7755d84f45d7a98cb6b3c1edd9817ae16e9/crates/core/src/user_config.rs#L28-L41

This seems to be an issue with serde, though. [Here](https://github.com/serde-rs/serde/issues/2638) is the only issue I was able to find on the topic.

### Any logs?

```
[DEBUG 2023-11-18 14:01:05] proto  Running proto v0.23.0  args=["proto", "run", "deno", "--log", "trace"]
[TRACE 14:01:05] starbase::app  Running startup phase with 1 systems 
[TRACE 14:01:05] starbase::app  Running analyze phase with 1 systems 
[TRACE 14:01:05] starbase::app  Running execute phase with 2 systems 
[DEBUG 14:01:05] proto_core::tool_loader:run  Traversing upwards to find a configured plugin  tool="deno"
[DEBUG 14:01:05] proto_core::tools_config:run  Loading .prototools  file="/home/ugudango/Projects/biomejs/resources-fork/.prototools"
[TRACE 14:01:05] starbase_utils::fs:run  Reading file  file="/home/ugudango/Projects/biomejs/resources-fork/.prototools"
[TRACE 14:01:05] starbase::app  Running shutdown phase with 1 systems 
Error:   × TOML parse error at line 1, column 1
  │   |
  │ 1 | auto-install = true
  │   | ^^^^^^^^^^^^^^^^^^^
  │ invalid type: boolean `true`, expected a string
  │ 
```

### Operating system?

Linux

### Architecture?

x64

**Comment by milesj** [comment]
@ugudango `auto-install` goes in `~/.proto/config.toml`, not `.prototools`. 

https://moonrepo.dev/docs/proto/config#user-configuration
