### ISSUE TITLE
proto direction: lanaguages or any tool?

### ISSUE THREAD

**Issue by tomdavidson** [moonrepo/proto#30]
Docs appear proto will install languages and their respective package managers, but #15  and #16  are for individual cli tools and the proto cli is quite similar to asdf's.

Will proto be analogs of the likes of asdf and brew or more along the lines of nvm, rvm and what not?

**Comment by itsezc** [comment]
Personally, I'd like to see a fusion of both: have Proto installed, define your project's dependencies: whether a language or a CLI tool and have it install / configure and ready to go for the dev.

**Comment by milesj** [comment]
It's main focus right now is languages/dependency managers, and definitely aligns closely with asdf. I'd say in the long run that proto is a better choice because it's written in Rust and is cross-platform.

I am looking to build a plugin system, which would unlock non-language kind of tools.

**Comment by tomdavidson** [comment]
Nice and thanks.   As for that plugin system, a vast majority of asdf plugins do exactly the same thing installing binaries from GitHub releases - almost like having a different plugin for each npm package.

Would be neat if proto could install GitHub releases generally (maybe for  nixpkgs too).

**Comment by milesj** [comment]
That's basically how Deno/Bun works. Just installs GH releases.

**Comment by RichiCoder1** [comment]
It'd probably spiral a bit complexity wise, but a generic github-release with some allowances to map tags => semvar and release assets => on-disk binary would cover a ton of cases at this point.

**Comment by tomvdsom** [comment]
For the tool-direction idea bucket: have a look at Volta https://volta.sh, the autoinstall on cd-into-project is nice.


A hybrid of asdf’s generic-ness and volta’s automate-so-you-can’t-forget would be very much appreciated 😉

**Comment by milesj** [comment]
@tomvdsom This is technically possible now!

With proto's dynamic version detection (https://moonrepo.dev/docs/proto/detection) and `auto-install` setting (https://moonrepo.dev/docs/proto/config#user-configuration), you can get a similar experience.

**Comment by tomdavidson** [comment]
diggin the design of the dynamic version detection!

**Comment by milesj** [comment]
Since we plan to support plugins (https://github.com/moonrepo/proto/issues/73), we're going to keep proto's built-in tools being languages and dependency managers only. For other kinds of tools, like CLIs, those should be implemented by the community as a plugin.
