### ISSUE TITLE
Canary / nightly versions of languages?

### ISSUE THREAD

**Issue by itsezc** [moonrepo/proto#31]
Would it be possible to use nightly versions of languages i.e. Bun which is almost v1 but still on 0.5, and expecting releases up to 0.7 has `bun upgrade --canary`, there are other languages and CLIs that have this problem / opportunity

**Comment by milesj** [comment]
Yeah it's on my list. I need to figure out the best way to support it that's generic enough for all languages.

**Comment by milesj** [comment]
@itsezc I've started looking into this, but I'm not sure how to implement it in a generic fashion.

Most tools/languages don't have a canary type of system, and when they do, they're all quite different in how they function.

Do you happen to know of a 3rd party version manager that supports canary? Curious how they are tackling it.

**Comment by itsezc** [comment]
I've been using asdf, and for neovim atleast there is: https://github.com/richin13/asdf-neovim and maybe it's worth looking into Scoop: https://github.com/neatorobito/scoop-crystal from what I've seen it supports alot of nightly packages.

**Comment by milesj** [comment]
Found a solution, now in 0.17!
