### ISSUE TITLE
`engines` handling is too strict?

### ISSUE THREAD

**Issue by TimonVS** [moonrepo/proto#33]
I have Node 16.14.2 and npm 8.5.0 installed, I would expect this to work with `engines` configured like so:

```json
{
    ...
    "engines": {
        "node": ">=16.13.0",
        "npm": ">=8.1.0"
    }
}
```

Instead I get an error when invoking either `node` or `npm`:

```
Attempted to run npm v8.1, but this version has not been installed. Install it with `proto install npm 8.1`!
```

Using `^` or `~` instead of `>=` gives the same result.

This is in a project with no other versioning files. I'm using the latest version of proto at the time of writing (0.2.1.)

**Comment by milesj** [comment]
@TimonVS Yeah version ranges with `>=` are... complicated. I expected the 8.1 to be resolved to the latest 8.1.x version at minimum.

Do you happen to know how volta handles this?

**Comment by TimonVS** [comment]
Volta doesn't support lookup from the `engines` field in `package.json` (nor does it support `.nvmrc`/`.node-version` for that matter). The closest equivalent in Volta is `volta pin` which pins to an exact version.

**Comment by milesj** [comment]
Good to know thanks. Also curious, how do you expect this to work?

With `>=` and your example above, I'm assuming it should just be "latest". But this isn't really ideal because it will constantly cause users to install new versions. Hrmm...

**Comment by TimonVS** [comment]
Yeah, alternatively you'd probably have to introduce a new caching mechanism where you store the result in `<project>/node_modules/.proto/npm/manifest` and install only when the requirement is not met. Though I can imagine that being quite a lot of work for a feature that may not be used all that often. On the other hand, I can imagine that there are teams writing apps that will use only the `engines` field, as the data may be consumed by other tools (think hosting providers), and they may not want to duplicate the source of truth in two separate files. Libraries probably shouldn't be using the `engines` field for this, as it limits the engines that can be used by the consumer (usually for no good reason).

I should expand on my use case for this. We have certain projects that require a specific version of npm to be used. We use `.nvmrc` to indicate which version of Node should be used, we expect people to use the version of npm that is bundled with this version of Node (that's how nvm behaves AFAIK). Proto however doesn't use the bundled version of npm, I assume it will use the global version unless a version is specified in `.prototools` or `package.json#engines`. I don't want to add `.prototools` to our projects (yet!) until the tool has proven itself.

All of that being said, our problem is actually solved by pinning npm with the `packageManager` field in `package.json` 😄.

**Comment by milesj** [comment]
Makes sense, thanks for the feedback. This should all be doable.

**Comment by milesj** [comment]
Ended up with this solution for now: https://github.com/moonrepo/proto/pull/37

**Comment by TimonVS** [comment]
Thank you Miles! I'll see if I can get the unreleased version to compile locally to give this and #32 a try!

**Comment by TimonVS** [comment]
I may have discovered a small bug, when I run `node -v` in a folder with `.nvmrc` containing `16.14.2` I first get this:

```shell
$ node -v
Attempted to run Node.js vv16.14.2, but this version has not been installed. Install it with `proto install node v16.14.2`!

$ proto install node v16.14.2
[INFO  proto:install] Installing Node.js with version "v16.14.2"
Failed to download tool from https://nodejs.org/dist/v16.14.2/node-v16.14.2-darwin-x64.tar.gz: 500 Internal Server Error
```

Notice the double v in "Node.js vv16.14.2". Then when I ran it without the `v` prefix I got another error (and I had to wait for multiple minutes for it to finish/fail):

```
$ proto install node 16.14.2
[INFO  proto:install] Installing Node.js with version "16.14.2"
HTTP failure for https://nodejs.org/dist/v16.14.2/node-v16.14.2-darwin-x64.tar.gz: request or response body error: error reading a body from connection: stream error received: unexpected internal error encountered
```

When I ran the command again it worked fine. Should this be counted as a hiccup with https://node.js.org? Or maybe I did something wrong building Proto locally (I ran `cargo build --release`, copied `target/release/proto` to `~/.proto-2/bin` and updated `.zshrc` to set `PROTO_ROOT` to `$HOME/.proto-2`).

**Comment by milesj** [comment]
@TimonVS A lot of my tests were timing out yesterday, so I believe nodejs.org was having problems.

As for the double v, easy enough fix.

**Comment by milesj** [comment]
Released 0.3

**Comment by TimonVS** [comment]
Thanks for the amazing work. It works great now!

**Comment by milesj** [comment]
Awesome!
