### ISSUE TITLE
Proto install prints "latest" when installing canary

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#332]
### What version?

0.25.0

### Which command?

proto install

### What happened?

When installing canary versions, `proto install node --canary` prints "Installing Node.js latest". Similar for `deno`.

This seems to be text only; it seems to install the canary version and adding `--pin` causes the canary version to be pinned as expected.

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
Fixed
