### ISSUE TITLE
`.prototools` should allow `[versions]` header

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#333]
### What version?

0.25.0

### What happened?

`proto debug config` prints all configured tool versions under a `[versions]` header like:

```toml
[versions]
deno = "latest"
node = "stable"
```

This is slightly misleading, since if you try to put a `versions` table in your actual `.prototools` file, you get the error:

```ShellSession
> Error: config::validate::failed

  × Failed to validate ~\.proto\.prototools.
  ╰─▶ · versions: unknown field `versions`

  help: https://moonrepo.dev/docs/proto/config
```

I personally like the `versions` heading, especially since it gives the flexibility to put version specifiers at the bottom of my config file (whereas root table entries must be *before* any TOML table headers).

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
This actually seems to be a bug in serde. The `versions` field uses `#[serde(flatten)]` but it doesn't flatten when serializing :/

I don't really want to support 2 ways of configuring the versions.

**Comment by rotu** [comment]
> Need to figure out why.

We have two `flatten` fields, one of them with `#[serde(skip_serializing)]` and I'm guessing that's the why.
https://github.com/moonrepo/proto/blob/7bf0abc7f3ecc8238a01872a63b47eb1299f3baa/crates/core/src/proto_config.rs#L98-L103

Maybe we should have a custom deserializer for the `unknown` field to update the `versions` property instead of [massaging the struct after deserialization](https://github.com/moonrepo/proto/blob/7bf0abc7f3ecc8238a01872a63b47eb1299f3baa/crates/core/src/proto_config.rs#L223-L227).

Possibly related? https://github.com/serde-rs/serde/issues/1504

**Comment by milesj** [comment]
Figured out the serde problem

**Comment by rotu** [comment]
The bug part of this is fixed :-). If you think it's not worth changing the `toml`, you can of course close this issue.

**Comment by milesj** [comment]
Looked into this a bit and it made it rather difficult to support both patterns.
