### ISSUE TITLE
First proto debug log statement in the wrong timezone

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#360]
### What version?

0.23.0

### What happened?

The first log statement emitted by `proto` is in a different format from the other logging statements. In particular, "Running proto" uses my local time zone for the timestamp but all other logging statements use UTC.
```ShellSession
$ proto use --log debug 
[DEBUG 2023-12-24 17:23:23] proto  Running proto v0.26.0  bin="proto" args=["use", "--log", "debug"] pid=97537
[DEBUG 23:23.161] proto_core::proto:detect_proto_env  Creating proto environment, detecting store  store="/Users/dan/.proto"
[DEBUG 23:23.161] proto_core::proto_config:load_proto_configs  Loading .prototools  file="/Users/dan/Source/proto/.prototools"
[DEBUG 23:23.162] proto_core::proto_config:load_proto_configs  Loading .prototools  file="/Users/dan/.proto/.prototools"
```

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
This is actually in starbase, but it's also weird since they're both the same local time variable: https://github.com/moonrepo/starbase/blob/master/crates/framework/src/tracing.rs#L71

**Comment by milesj** [comment]
Oh I think you're confused because the short format is just minutes, seconds, and nanoseconds. It's not hour/minute.

**Comment by rotu** [comment]
> Oh I think you're confused because the short format is just minutes, seconds, and nanoseconds. It's not hour/minute.

You are right - the format confused me. Even after definitely noticing the format, it still confused me. maybe:
- the hours should be kept in the timestamp
- messages should stamped with the *duration* the process has been running instead of the partial time
- use the ISO 8601 format for truncated time with a leading `-` e.g. `-23:23.161` (though I think this format is deprecated)

if you think it’s okay as-is, you can close this issue

**Comment by milesj** [comment]
Added the hours to it.
