### ISSUE TITLE
Setup for Elvish shell is not working as intended

### ISSUE THREAD

**Issue by frantic1048** [moonrepo/proto#361]
### What version?

0.26.0

### Which command?

curl -fsSL https://moonrepo.dev/install/proto.sh | bash

## Problem

**Elvish version**: 0.19.2

After running installation script:

```sh
curl -fsSL https://moonrepo.dev/install/proto.sh | bash
```

It appends following code to `~/.config/elvish/rc.elv`

```elvish
# proto
set-env PROTO_HOME $HOME/.proto
set-env PATH (str:join ':' [$PROTO_HOME/shims:$PROTO_HOME/bin $E:PATH])
```

This will cause the following error:

```
Multiple compilation errors in /Users/kafuuchino/.config/elvish/rc.elv:
  variable $HOME not found
    27:20: set-env PROTO_HOME $HOME/.proto
  variable $PROTO_HOME not found
    28:29: set-env PATH (str:join ':' [$PROTO_HOME/shims:$PROTO_HOME/bin $E:PATH])
  variable $PROTO_HOME not found
    28:47: set-env PATH (str:join ':' [$PROTO_HOME/shims:$PROTO_HOME/bin $E:PATH])
```

The correct code could be:

```elvish
# proto

# PROTO_HOME
set-env PROTO_HOME {~}/.proto

# PATH

# via string concat, add the missing `E:` prefix
set-env $PATH (str:join ':' [
  $E:PROTO_HOME/shims
  $E:PROTO_HOME/bin
  $E:PATH
])

# or via special paths variable for easier edit
set paths = [
  $E:PROTO_HOME/shims
  $E:PROTO_HOME/bin
  $@paths
]
```

## Explanation

To reference an environment variable named `PROTO_HOME`, either prefix with `E:` or use `get-env` builtin:
- not work: `echo $PROTO_HOME`: this is a reference to local variable named `PROTO_HOME`, not environment variable.
- works: `echo $E:PROTO_HOME` or `echo (get-env PROTO_HOME)`

## References

- dedicated `E:` namespace for environment variables: https://elv.sh/ref/language.html#special-namespaces
- `get-env`: https://elv.sh/ref/builtin.html#get-env
- Special `$paths` builtin variable for easier operating of `$E:PATH`, `$paths` is a list form of `$E:PATH`, allowing list operations to be directly applied to `$E:PATH`: https://elv.sh/ref/builtin.html#$paths

### Operating system?

MacOS

### Architecture?

x64

**Comment by milesj** [comment]
Thanks! The examples I looked at must of been wrong :P

I believe this will fix it https://github.com/moonrepo/proto/pull/362

**Comment by frantic1048** [comment]
It looks fine, thanks for the blazing fast fix and the cool work 💯
