### ISSUE TITLE
Contributing Guidance

### ISSUE THREAD

**Issue by RichiCoder1** [moonrepo/proto#39]
Howdy! I'd be interested in contributing #14, but I noticed there was no `CONTRIBUTING.md` or anything like it. Is there any guidance for someone looking to contribute?

**Comment by milesj** [comment]
I'll look into adding this.

As for #14, let's hold off a bit until I figure out how to move forward for non-language based tools.

**Comment by RichiCoder1** [comment]
Terraform _sorta_ is a language tool (HCL), but I understand it not fitting the normal model of existing languages.
