### ISSUE TITLE
How to install a tool from a .dmg package? (macos, TOML plugin)

### ISSUE THREAD

**Issue by alexbepple** [moonrepo/proto#391]
I am trying to write a TOML plugin for [aws-vault](https://github.com/99designs/aws-vault). However, its macos binaries are packaged as .dmg files, cp. https://github.com/99designs/aws-vault/releases.

I have had no success with, nor without `unpack = false` in the `install` section of the TOML file.

Here is the current state of the plugin: https://gist.github.com/alexbepple/ae7de660a3a4925dcf3b504832520b90.
Listing versions works. Downloading works. `proto` even claims that the tool is successfully installed. However, when I run it, I see the following (plenty of control chars there, so this is not exact):

```
❯ aws-vault -h
/Users/ab/.proto/tools/aws-vault/6.6.0/aws-vault: line 1: xsu�p
                                                               : command not found
/Users/ab/.proto/tools/aws-vault/6.6.0/aws-vault: line 2: syntax error near unexpected token `�!��'
Wy*��cq�Z��_3T�H���]���(�!��>xc`C8������^���t��� line 2{x��1�q���R%'nrHyp}/�V��A���
```

**Comment by milesj** [comment]
@alexbepple Unfortunately only zip/tar is supported for TOML plugins right now.

You would need to build your own WASM plugin and implement your own function for unpacking to support other formats: https://moonrepo.dev/docs/proto/wasm-plugin#unpacking-an-archive

**Comment by alexbepple** [comment]
Thanks for the quick response, @milesj.

Unfortunately I don’t see myself taking that deep dive any time soon. I have never worked with WASM or Rust before.

How far down the priority list would this be for you? ;-)

**Comment by milesj** [comment]
I'm not really sure all what's involved for `.dmg` files, so can't say right now.

**Comment by alexbepple** [comment]
Alright. I will stop bugging you. :-)

One last note. My quick research found this: https://crates.io/crates/dmgwiz. But I have no idea how reusable this would be.
