### ISSUE TITLE
Automatic Installation

### ISSUE THREAD

**Issue by RichiCoder1** [moonrepo/proto#40]
Coming from other tools, they would (with some exceptions) automatically install the appropriate runtime if a shim was referenced and the appropriate versions were correct. This is super helpful especially when the runtime version changes reasonably frequently due to maintenance automation bots like Renovate/Dependabot.

Don't know if a good default would be on-by-default or not, but would love to have the option!

**Comment by milesj** [comment]
Yeah I've thought about this quite a lot. My only concern is the tool unnecessarily installing a ton of unneeded versions, but maybe putting this behind a setting isn't a bad idea.

**Comment by RichiCoder1** [comment]
> Yeah I've thought about this quite a lot. My only concern is the tool unnecessarily installing a ton of unneeded versions, but maybe putting this behind a setting isn't a bad idea.

I had that exact same thought. Maybe a long-term feature could be GC for unused runtimes, but I imagine that'd be an epic unto itself.

**Comment by milesj** [comment]
Landed in 0.4.
