### ISSUE TITLE
PowerShell Profile isn't setup when OneDrive Known Folder Redirection is enabled

### ISSUE THREAD

**Issue by collinstevens** [moonrepo/proto#404]
### What version?

0.29.1

### What happened?

On installation of proto, it fails to setup the PowerShell profile if OneDrive Known Folder Redirection is enabled.

In my case, on client laptops, OneDrive is usually enforced through Group Policy and forces the Documents folder to be backed up which causes OneDrive to redirect it to the OneDrive version of the Documents folder.

The PowerShell $PROFILE variable uses the Personal variable from the Registry to determine the Current User's Documents folder, which will be overridden when OneDrive Known Folder Redirection is enabled.

Here is a resource detailing all the registry keys for folder locations https://www.winhelponline.com/blog/windows-10-shell-folders-paths-defaults-restore/.

Here is an example of what my personal desktop's values are 
![image](https://github.com/moonrepo/proto/assets/19230602/baa97fb2-d6fb-4634-b1b4-5b0736af7d87)

Here is an example of a laptop with OneDrive enabled on it and it's values are 
![image](https://github.com/moonrepo/proto/assets/19230602/6ab51289-1de4-46ce-8cd1-001819939f30)

Notice the existence of the `{F42EE2D3-909F-4907-8871-4C22FC0BF756}` key to indicate the Documents folder has been redirected and also notice the value of the Personal key is the OneDrive version of the Documents folder.

You should be able to use the value of the Personal registry key always without checking for OneDrive and calculate the path of the Current User All Hosts PowerShell profile using https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4#profile-types-and-locations.

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
Updated to use `documents_dir()`: https://github.com/moonrepo/proto/pull/407/files#diff-35d1056bc75f3dbb7b95634bb9fd1ed1b0272b4e595651f0251d14522fa2597fR66

After looking at their source, they do some windows registry magic, so hopefully this works.

**Comment by collinstevens** [comment]
> I think v0.30 should help here.

Yup, I was prompted for the CurrentUserAllHosts or CurrentUserCurrentHost location for PowerShell Core profiles.

This will work well enough for me, but will not work for WIndows PowerShell or Command Prompt users which may hurt adoption in the future, but good enough for me at the moment.
