### ISSUE TITLE
Proto Node.js can't execute `corepack`

### ISSUE THREAD

**Issue by ImBIOS** [moonrepo/proto#428]
### What version?

0.31.2

### Which command?

corepack

### What happened?

I wanna install yarn using corepack, but:

```
via  v18.19.1 
 ✗  corepack
zsh: command not found: corepack
```

### Trace logs?

_dunno what command should I run_

### Operating system?

Linux

### Architecture?

x64

**Comment by ImBIOS** [comment]
Now I'm:

```
via 🍞 v1.0.30 via  v18.19.1 
 ➜  npm install -g corepack

changed 1 package in 2s
```

then:

```
 via 🍞 v1.0.30 via  v18.19.1   3s 
 ➜  corepack enable
zsh: command not found: corepack
```

then:

```
 via 🍞 v1.0.30 via  v18.19.1 
 ✗  npm -g list            
/home/imbios/.proto/tools/node/18.19.1/lib
├── corepack@0.25.2
└── npm@10.2.4
```

**Comment by ImBIOS** [comment]
My bad, I found it here, thanks. https://moonrepo.dev/docs/proto/tools 😢

**Comment by milesj** [comment]
@ImBIOS curious why you want to use corepack to install yarn, when you could use proto?

**Comment by ImBIOS** [comment]
@milesj The story is that it's my first `yarn` project that I wanna contribute to since I'm switching to `proto`, then I found out that I don't have `yarn` yet, so checked the `yarn` docs and found that it's recommended to use `corepack` to install `yarn`.

That's it, there's no other reason, so it's solved by reading `proto` docs ( https://moonrepo.dev/docs/proto/tools )
