### ISSUE TITLE
Improve error message when xz is not installed in the system

### ISSUE THREAD

**Issue by JLarky** [moonrepo/proto#437]
### Which command?

curl -fsSL https://moonrepo.dev/install/proto.sh | bash

### What happened?

proto error message:
```
$ curl -fsSL https://moonrepo.dev/install/proto.sh | bash

######################################################################## 100.0%
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

compare that to error message Bun shows when you are missing unzip:

```
$ curl -fsSL https://bun.sh/install | bash
error: unzip is required to install bun (see: https://bun.sh/docs/installation#macos-and-linux)
```

### Operating system?

Linux

### Architecture?

x64

**Comment by milesj** [comment]
We use `tar xf` to unpack. I'll see if there's a way to detect what tar requires.

**Comment by milesj** [comment]
I think this will do it? https://github.com/moonrepo/moon/pull/1387

**Comment by milesj** [comment]
Should error now.

**Comment by JLarky** [comment]
Thank you, looks great now
