### ISSUE TITLE
npx not found

### ISSUE THREAD

**Issue by TimonVS** [moonrepo/proto#44]
After installing Node and npm with Proto, I'm unable to use `npx`. I don't see `npx` in the `~/.proto/bin` folder, I think it should be there?

```console
$ proto install node 18
[INFO  proto:install] Installing Node.js with version "18"
[INFO  proto:install] Node.js has been installed at /Users/timon.vanspronsen/.proto/tools/node/18.15.0!
[INFO  proto:install] Installing npm with version "bundled"
[INFO  proto:install] npm has been installed at /Users/timon.vanspronsen/.proto/tools/npm/9.5.0!
$ proto global node 18
[INFO  proto:global] Set the global Node.js version to 18
$ proto global npm 9.5.0
[INFO  proto:global] Set the global npm version to 9.5.0
$ npx
zsh: command not found: npx
```

**Comment by milesj** [comment]
Definitely an oversight! Should be an easy fix.

**Comment by RichiCoder1** [comment]
> Definitely an oversight! Should be an easy fix.

I can make it separate ticket, but could `pnpm` (and maybe `yarn`) also get coverage? This is especially important when using `corepack`.

**Comment by milesj** [comment]
Those 2 require a version number to install with, while npx/npm do not. I'll think about it.

**Comment by RichiCoder1** [comment]
> Those 2 require a version number to install with, while npx/npm do not. I'll think about it.

That's fair. I'd take a flag too, but with [corepack](https://github.com/nodejs/corepack#usage) the version is baked into the package.json. However, I could see that being somewhat at odds with having everything in `prototools` so I don't feel strongly about it!

**Comment by milesj** [comment]
Ok fixed. You'll need to run a node command to regenerate the shims.
