### ISSUE TITLE
proto doesn't really work on windows

### ISSUE THREAD

**Issue by lagz0ne** [moonrepo/proto#46]
**Version**
0.3.0 using 0.3.1 script

**reproduce**
- added .proto\bin to PATH (set manually, the script doesn't do that)
- install any components, for example node
- call `node`
- error displayed

**error details**

```
.proto\bin\node.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ node
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**expect**

can use installed components

**Comment by milesj** [comment]
@lagz0ne Just to clarify, the `proto` commands work, like `proto install`, etc, but actually running the shims for the tools does not?

**Comment by milesj** [comment]
Also if you run `Set-ExecutionPolicy RemoteSigned` in powershell, does it solve the problem?

**Comment by lagz0ne** [comment]
```
Set-ExecutionPolicy : Access to the registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' is denied. To change the execution policy for the default (LocalMachine)
scope, start Windows PowerShell with the "Run as administrator" option. To change the execution policy for the current user, run "Set-ExecutionPolicy -Scope CurrentUser".
At line:1 char:1
+ Set-ExecutionPolicy RemoteSigned
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
```

using non-admin shell

Then I follow the hint, adding `Set-ExecutionPolicy -Scope CurrentUser RemoteSigned`, so I can call `node`

**Comment by lagz0ne** [comment]
`Set-ExecutionPolicy RemoteSigned` in Admin shell does the work, but that means the whole installation should be done in a Admin shell

**Comment by milesj** [comment]
Thanks for this, I'll update the docs.

**Comment by lagz0ne** [comment]
I can install node but I cannot install go. It requires git. That should be updated as well

**Comment by lagz0ne** [comment]
ON Windows, I think you should consider winget

**Comment by milesj** [comment]
Updated the docs with all these examples. Gonna close this.
