### ISSUE TITLE
proto outdated --update clobbers non-version settings

### ISSUE THREAD

**Issue by rotu** [moonrepo/proto#461]
### What version?

0.34.3

### Which command?

proto outdated --update

### What happened?

I start with a local `.prototools` with some settings in it:

```yaml
# a comment
node = "21.0.0"

[env]
DEBUG = false
```

Then run `proto outdated --update` and accept updates.

```console
> proto outdated --update

 Tool  Current  Newest  Latest  Config                 
 node  21.0.0   21.7.3  21.7.3  /Users/dan/.prototools 

✔ Update config files with newest versions? · yes
Updating ~/.prototools with 1 versions
Update complete! Run proto use to install these new versions.
```

Looking at the `.prototools` file again, the version has been updated but the comment and `[env]` section have been stripped out
```yaml
node = "21.7.3"

```

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
🤔 

This is the same code that all the other commands use...
