### ISSUE TITLE
[Windows] "proto regen [--bin]" always throws the error "proto::tool::invalid_dir"

### ISSUE THREAD

**Issue by wathhr** [moonrepo/proto#477]
### What version?

0.35.2

### Which command?

proto regen

### What happened?

When attempting to run `proto regen` either with or without the `--bin` flag I get the following error: `inventory directory has been overridden but is not an absolute path. Only absolute paths are supported.` (proto::tool::invalid_dir)

### Trace logs?

[DEBUG 2024-05-17 18:20:52.515] proto  Running proto v0.35.2  bin="proto" args=["regen", "--log=trace"] pid=6712
[TRACE 18:20:52.516] starbase::app  Running startup phase with 2 systems
[DEBUG 18:20:52.518] proto_core::proto  Creating proto environment, detecting store  store="C:\\Users\\wathhr\\.proto"
[TRACE 18:20:52.518] starbase::app  Running analyze phase with 2 systems
[TRACE 18:20:52.519] proto_core::proto_config  Traversing upwards and loading .prototools files
[DEBUG 18:20:52.519] proto_core::proto_config  Loading .prototools  file="C:\\Users\\wathhr\\.prototools"
[TRACE 18:20:52.520] starbase_utils::fs  Reading file  file="C:\\Users\\wathhr\\.prototools"
[TRACE 18:20:52.520] schematic::config::loader  Loading partial configuration  config="ProtoConfig"
[TRACE 18:20:52.520] schematic::config::loader  Creating layer from source  config="ProtoConfig" source="\<code>"
[TRACE 18:20:52.522] schematic::config::loader  Merging partial layers into a final result  config="ProtoConfig"
[DEBUG 18:20:52.522] proto_core::proto_config  Loading .prototools  file="C:\\Users\\wathhr\\.proto\\.prototools"
[TRACE 18:20:52.522] starbase_utils::fs  Opening file  file="C:\\Users\\wathhr\\.proto\\.prototools"
[TRACE 18:20:52.523] starbase_utils::fs_lock  Locking file  file="C:\\Users\\wathhr\\.proto\\.prototools"
[TRACE 18:20:52.523] starbase_utils::fs_lock  Unlocking file  file="C:\\Users\\wathhr\\.proto\\.prototools"
[TRACE 18:20:52.523] schematic::config::loader  Loading partial configuration  config="ProtoConfig"
[TRACE 18:20:52.524] schematic::config::loader  Creating layer from source  config="ProtoConfig" source="\<code>"
[TRACE 18:20:52.524] schematic::config::loader  Merging partial layers into a final result  config="ProtoConfig"
[DEBUG 18:20:52.525] proto_core::proto_config  Merging loaded configs
[DEBUG 18:20:52.525] proto_core::proto_config  Merged 2 configs
[TRACE 18:20:52.526] starbase::app  Running execute phase with 3 systems
[TRACE 18:20:52.526] starbase_utils::net  Checking for an internet connection  timeout=750
[TRACE 18:20:52.527] starbase_utils::net::offline  Resolving 1.1.1.1:53
[TRACE 18:20:52.534] starbase_utils::net  Online!
[TRACE 18:20:52.535] starbase_utils::fs  Reading file  file="C:\\Users\\wathhr\\.proto\\temp\\.last-version-check"
[DEBUG 18:20:52.535] proto::commands::regen  Removing old shims
[DEBUG 18:20:52.536] proto::commands::regen  Loading tools
[DEBUG 18:20:52.536] proto_core::proto_config  Loading global config only
[DEBUG 18:20:52.536] proto_core::proto_config  Merged 1 configs
[DEBUG 18:20:52.536] proto_core::tool_loader  Finding a configured plugin  tool="internal-schema"
[DEBUG 18:20:52.536] proto_core::tool_loader  Using a built-in plugin  plugin="source:https://github.com/moonrepo/schema-plugin/releases/download/v0.12.0/schema_plugin.wasm"
[TRACE 18:20:52.537] warpgate::loader  Creating plugin loader  cache_dir="C:\\Users\\wathhr\\.proto\\plugins"
[TRACE 18:20:52.537] warpgate::loader  Loading plugin internal-schema  id="internal-schema"
[TRACE 18:20:52.537] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\internal-schema-e6060c7fc658d929dfd3b1b9897075a3b7509fbda52718d52f37b7e663b7f300.wasm"
[TRACE 18:20:52.538] warpgate::loader  Plugin already downloaded and cached  id="internal-schema" path="C:\\Users\\wathhr\\.proto\\plugins\\internal-schema-e6060c7fc658d929dfd3b1b9897075a3b7509fbda52718d52f37b7e663b7f300.wasm"
[TRACE 18:20:52.539] warpgate::loader  Loading plugin yarn  id="yarn"
[TRACE 18:20:52.539] warpgate::loader  Loading plugin deno  id="deno"
[TRACE 18:20:52.539] warpgate::loader  Loading plugin rust  id="rust"
[TRACE 18:20:52.539] warpgate::loader  Loading plugin npm  id="npm"
[TRACE 18:20:52.540] warpgate::loader  Loading plugin python  id="python"
[TRACE 18:20:52.539] warpgate::loader  Loading plugin bun  id="bun"
[TRACE 18:20:52.540] warpgate::loader  Loading plugin node  id="node"
[TRACE 18:20:52.539] warpgate::loader  Loading plugin pnpm  id="pnpm"
[TRACE 18:20:52.540] warpgate::loader  Loading plugin go  id="go"
[TRACE 18:20:52.543] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\rust-3919b0e80276af804a976a487aa9c7b4d1c1ace0a5066482442ad258fb52d3af.wasm"
[TRACE 18:20:52.543] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\deno-4a28c4d1103acbb4cd2d705d5f469683f0bd34cb21148b9d37b301b80c519bfa.wasm"
[TRACE 18:20:52.543] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\npm-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[TRACE 18:20:52.543] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\python-28e622f91be0a54593717eb9192f28ddfb8dd26e73fd2dbc4117c4a964ea6b3c.wasm"
[TRACE 18:20:52.544] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\yarn-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[TRACE 18:20:52.544] warpgate::loader  Plugin already downloaded and cached  id="rust" path="C:\\Users\\wathhr\\.proto\\plugins\\rust-3919b0e80276af804a976a487aa9c7b4d1c1ace0a5066482442ad258fb52d3af.wasm"
[TRACE 18:20:52.544] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\node-5d5550b55f5c078b44f6f3d18848c08a0274704bdd236ba3a4a71cf8a24c02eb.wasm"
[TRACE 18:20:52.545] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\go-b94b60b5275679862981cacc47cf50a9d7cd49c178843b5feb6e57e0cadea906.wasm"
[TRACE 18:20:52.545] warpgate::loader  Plugin already downloaded and cached  id="deno" path="C:\\Users\\wathhr\\.proto\\plugins\\deno-4a28c4d1103acbb4cd2d705d5f469683f0bd34cb21148b9d37b301b80c519bfa.wasm"
[TRACE 18:20:52.545] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\pnpm-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[TRACE 18:20:52.546] starbase_utils::fs  Reading file metadata  file="C:\\Users\\wathhr\\.proto\\plugins\\bun-fa4e348862469aa825121e1108cfad8b9e2ea77a1b2eeb0e4b7a8dbadf593415.wasm"
[TRACE 18:20:52.546] warpgate::loader  Plugin already downloaded and cached  id="python" path="C:\\Users\\wathhr\\.proto\\plugins\\python-28e622f91be0a54593717eb9192f28ddfb8dd26e73fd2dbc4117c4a964ea6b3c.wasm"
[TRACE 18:20:52.546] warpgate::loader  Plugin already downloaded and cached  id="npm" path="C:\\Users\\wathhr\\.proto\\plugins\\npm-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[TRACE 18:20:52.547] warpgate::loader  Plugin already downloaded and cached  id="yarn" path="C:\\Users\\wathhr\\.proto\\plugins\\yarn-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[DEBUG 18:20:52.547] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\rust-3919b0e80276af804a976a487aa9c7b4d1c1ace0a5066482442ad258fb52d3af.wasm"
[TRACE 18:20:52.547] warpgate::loader  Plugin already downloaded and cached  id="pnpm" path="C:\\Users\\wathhr\\.proto\\plugins\\pnpm-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[TRACE 18:20:52.547] warpgate::loader  Plugin already downloaded and cached  id="go" path="C:\\Users\\wathhr\\.proto\\plugins\\go-b94b60b5275679862981cacc47cf50a9d7cd49c178843b5feb6e57e0cadea906.wasm"
[DEBUG 18:20:52.548] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\deno-4a28c4d1103acbb4cd2d705d5f469683f0bd34cb21148b9d37b301b80c519bfa.wasm"
[TRACE 18:20:52.547] warpgate::loader  Plugin already downloaded and cached  id="node" path="C:\\Users\\wathhr\\.proto\\plugins\\node-5d5550b55f5c078b44f6f3d18848c08a0274704bdd236ba3a4a71cf8a24c02eb.wasm"
[DEBUG 18:20:52.548] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\npm-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[DEBUG 18:20:52.549] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\yarn-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[DEBUG 18:20:52.549] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\python-28e622f91be0a54593717eb9192f28ddfb8dd26e73fd2dbc4117c4a964ea6b3c.wasm"
[DEBUG 18:20:52.549] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\pnpm-26bb33b6307ed24c6c1940288bc216f80630ca5ad26be20c58c07240312f9602.wasm"
[TRACE 18:20:52.547] warpgate::loader  Plugin already downloaded and cached  id="bun" path="C:\\Users\\wathhr\\.proto\\plugins\\bun-fa4e348862469aa825121e1108cfad8b9e2ea77a1b2eeb0e4b7a8dbadf593415.wasm"
[DEBUG 18:20:52.550] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\go-b94b60b5275679862981cacc47cf50a9d7cd49c178843b5feb6e57e0cadea906.wasm"
[DEBUG 18:20:52.550] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\node-5d5550b55f5c078b44f6f3d18848c08a0274704bdd236ba3a4a71cf8a24c02eb.wasm"
[TRACE 18:20:52.550] warpgate::plugin  Storing plugin identifier  id="rust"
[TRACE 18:20:52.552] warpgate::plugin  Storing plugin identifier  id="npm"
[TRACE 18:20:52.552] warpgate::plugin  Storing plugin identifier  id="yarn"
[TRACE 18:20:52.551] warpgate::plugin  Storing plugin identifier  id="deno"
[TRACE 18:20:52.552] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[TRACE 18:20:52.552] warpgate::plugin  Storing plugin identifier  id="python"
[DEBUG 18:20:52.551] proto_core::tool_loader  Loading WASM plugin  source="C:\\Users\\wathhr\\.proto\\plugins\\bun-fa4e348862469aa825121e1108cfad8b9e2ea77a1b2eeb0e4b7a8dbadf593415.wasm"
[TRACE 18:20:52.554] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[TRACE 18:20:52.554] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[DEBUG 18:20:52.555] proto_core::tool  Creating tool rust and instantiating plugin
[TRACE 18:20:52.553] warpgate::plugin  Storing plugin identifier  id="pnpm"
[TRACE 18:20:52.554] warpgate::plugin  Storing plugin identifier  id="node"
[TRACE 18:20:52.554] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[TRACE 18:20:52.554] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[TRACE 18:20:52.553] warpgate::plugin  Storing plugin identifier  id="go"
[TRACE 18:20:52.556] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[DEBUG 18:20:52.555] proto_core::tool  Creating tool npm and instantiating plugin
[DEBUG 18:20:52.557] proto_core::tool  Creating tool yarn and instantiating plugin
[DEBUG 18:20:52.556] proto_core::tool  Creating tool deno and instantiating plugin
[TRACE 18:20:52.556] warpgate::plugin  Storing plugin identifier  id="bun"
[TRACE 18:20:52.556] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[DEBUG 18:20:52.557] proto_core::tool  Creating tool python and instantiating plugin
[TRACE 18:20:52.557] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[TRACE 18:20:52.559] starbase_utils::json  Formatting JSON
[TRACE 18:20:52.559] warpgate::plugin  Storing host environment  env={"arch":"x64","libc":"unknown","os":"windows","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"C:\\Users\\wathhr"}}
[DEBUG 18:20:52.560] proto_core::tool  Creating tool pnpm and instantiating plugin
[TRACE 18:20:52.560] proto_core::tool_loader  Storing proto tool configuration  config={}
[DEBUG 18:20:52.560] proto_core::tool  Creating tool go and instantiating plugin
[DEBUG 18:20:52.560] proto_core::tool  Creating tool bun and instantiating plugin
[DEBUG 18:20:52.561] proto_core::tool  Creating tool node and instantiating plugin
[TRACE 18:20:52.583] warpgate::plugin  Created plugin container  id="rust" plugin="0f60e1a7-918f-4df6-99b5-bd215c0306dc"
[DEBUG 18:20:52.584] proto_core::tool  Created tool rust and its WASM runtime
[TRACE 18:20:52.584] warpgate::plugin  Calling plugin function register_tool  id="rust" plugin="0f60e1a7-918f-4df6-99b5-bd215c0306dc" input={"id":"rust"}
[TRACE 18:20:52.584] warpgate::plugin  Created plugin container  id="go" plugin="fd6ec546-523e-4fc6-8a64-0acbc4a2abc2"
[TRACE 18:20:52.584] warpgate::plugin  Created plugin container  id="python" plugin="c698e708-7f9f-4820-8733-f25a84adb996"
[TRACE 18:20:52.585] warpgate::plugin  Created plugin container  id="deno" plugin="04e4bd41-26a3-4e38-8cbd-543e8dda1f18"
[DEBUG 18:20:52.586] proto_core::tool  Created tool python and its WASM runtime
[DEBUG 18:20:52.586] proto_core::tool  Created tool go and its WASM runtime
[TRACE 18:20:52.586] warpgate::plugin  Created plugin container  id="pnpm" plugin="156b8bc4-3ef1-45cb-9d34-a344fdb0c31a"
[DEBUG 18:20:52.586] proto_core::tool  Created tool deno and its WASM runtime
[TRACE 18:20:52.586] warpgate::plugin  Created plugin container  id="yarn" plugin="bbeecfe9-ddae-4337-a640-6b7dd779853e"
[TRACE 18:20:52.585] warpgate::plugin  Created plugin container  id="bun" plugin="98c8be47-e4ce-4733-a443-38ce6c613101"
[TRACE 18:20:52.586] warpgate::host_funcs  Read environment variable from host  name="RUSTUP_HOME" value="D:\\Scoop\\persist\\rustup\\.rustup"
[TRACE 18:20:52.588] warpgate::plugin  Created plugin container  id="node" plugin="243fde69-fff6-4fcc-a416-a25e32500026"
[TRACE 18:20:52.586] warpgate::plugin  Created plugin container  id="npm" plugin="4ea4f2cd-ebc1-4dcb-bf42-cd6ef1136be8"
[TRACE 18:20:52.588] warpgate::plugin  Calling plugin function register_tool  id="python" plugin="c698e708-7f9f-4820-8733-f25a84adb996" input={"id":"python"}
[DEBUG 18:20:52.589] proto_core::tool  Created tool bun and its WASM runtime
[DEBUG 18:20:52.590] proto_core::tool  Created tool node and its WASM runtime
[DEBUG 18:20:52.589] proto_core::tool  Created tool pnpm and its WASM runtime
[DEBUG 18:20:52.591] proto_core::tool  Created tool npm and its WASM runtime
[DEBUG 18:20:52.589] proto_core::tool  Created tool yarn and its WASM runtime
[TRACE 18:20:52.590] warpgate::plugin  Calling plugin function register_tool  id="go" plugin="fd6ec546-523e-4fc6-8a64-0acbc4a2abc2" input={"id":"go"}
[TRACE 18:20:52.591] warpgate::host_funcs  Converted a path into a virtual path  original_path="D:\\Scoop\\persist\\rustup\\.rustup/toolchains" virtual_path="D:\\Scoop\\persist\\rustup\\.rustup/toolchains"
[TRACE 18:20:52.591] warpgate::plugin  Calling plugin function register_tool  id="deno" plugin="04e4bd41-26a3-4e38-8cbd-543e8dda1f18" input={"id":"deno"}
[TRACE 18:20:52.591] warpgate::plugin  Called plugin function register_tool  id="python" plugin="c698e708-7f9f-4820-8733-f25a84adb996" output={"inventory":{},"name":"Python","plugin_version":"0.10.0","type":"Language"}
[TRACE 18:20:52.593] warpgate::plugin  Called plugin function register_tool  id="go" plugin="fd6ec546-523e-4fc6-8a64-0acbc4a2abc2" output={"inventory":{},"name":"Go","plugin_version":"0.11.1","type":"Language"}
[TRACE 18:20:52.593] warpgate::plugin  Calling plugin function register_tool  id="bun" plugin="98c8be47-e4ce-4733-a443-38ce6c613101" input={"id":"bun"}
[TRACE 18:20:52.593] warpgate::plugin  Calling plugin function register_tool  id="npm" plugin="4ea4f2cd-ebc1-4dcb-bf42-cd6ef1136be8" input={"id":"npm"}
[TRACE 18:20:52.592] warpgate::plugin  Calling plugin function register_tool  id="pnpm" plugin="156b8bc4-3ef1-45cb-9d34-a344fdb0c31a" input={"id":"pnpm"}
[TRACE 18:20:52.594] warpgate::plugin  Called plugin function register_tool  id="rust" plugin="0f60e1a7-918f-4df6-99b5-bd215c0306dc" output={"default_version":"stable","inventory":{"disable_progress_bars":true,"override_dir":"D:\\Scoop\\persist\\rustup\\.rustup/toolchains","version_suffix":"-x86_64-pc-windows-msvc"},"name":"Rust","plugin_version":"0.10.0","type":"Language"}
[TRACE 18:20:52.594] warpgate::plugin  Calling plugin function register_tool  id="yarn" plugin="bbeecfe9-ddae-4337-a640-6b7dd779853e" input={"id":"yarn"}
[DEBUG 18:20:52.594] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\python\\manifest.json"
[DEBUG 18:20:52.595] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\go\\manifest.json"
[TRACE 18:20:52.593] warpgate::plugin  Calling plugin function register_tool  id="node" plugin="243fde69-fff6-4fcc-a416-a25e32500026" input={"id":"node"}
[TRACE 18:20:52.595] warpgate::plugin  Called plugin function register_tool  id="bun" plugin="98c8be47-e4ce-4733-a443-38ce6c613101" output={"inventory":{},"name":"Bun","plugin_version":"0.12.0","self_upgrade_commands":["upgrade"],"type":"Language"}
[TRACE 18:20:52.595] warpgate::plugin  Called plugin function register_tool  id="deno" plugin="04e4bd41-26a3-4e38-8cbd-543e8dda1f18" output={"inventory":{},"name":"Deno","plugin_version":"0.11.0","self_upgrade_commands":["upgrade"],"type":"Language"}
[TRACE 18:20:52.596] warpgate::plugin  Called plugin function register_tool  id="pnpm" plugin="156b8bc4-3ef1-45cb-9d34-a344fdb0c31a" output={"inventory":{},"name":"pnpm","plugin_version":"0.11.0","type":"DependencyManager"}
[TRACE 18:20:52.596] warpgate::plugin  Called plugin function register_tool  id="npm" plugin="4ea4f2cd-ebc1-4dcb-bf42-cd6ef1136be8" output={"default_version":"bundled","inventory":{},"name":"npm","plugin_version":"0.11.0","type":"DependencyManager"}
[DEBUG 18:20:52.597] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\rust\\manifest.json"
[TRACE 18:20:52.596] warpgate::plugin  Called plugin function register_tool  id="yarn" plugin="bbeecfe9-ddae-4337-a640-6b7dd779853e" output={"inventory":{},"name":"yarn","plugin_version":"0.11.0","type":"DependencyManager"}
[DEBUG 18:20:52.598] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\bun\\manifest.json"
[TRACE 18:20:52.597] warpgate::plugin  Called plugin function register_tool  id="node" plugin="243fde69-fff6-4fcc-a416-a25e32500026" output={"inventory":{},"name":"Node.js","plugin_version":"0.11.0","type":"Language"}
[TRACE 18:20:52.597] starbase_utils::fs  Opening file  file="C:\\Users\\wathhr\\.proto\\tools\\python\\manifest.json"
[DEBUG 18:20:52.598] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\deno\\manifest.json"
[DEBUG 18:20:52.600] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\node\\manifest.json"
[DEBUG 18:20:52.598] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\pnpm\\manifest.json"
[DEBUG 18:20:52.599] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\npm\\manifest.json"
[DEBUG 18:20:52.600] proto_core::tool_manifest  Loading manifest.json  file="C:\\Users\\wathhr\\.proto\\tools\\yarn\\manifest.json"
[TRACE 18:20:52.600] starbase_utils::fs_lock  Locking file  file="C:\\Users\\wathhr\\.proto\\tools\\python\\manifest.json"
[TRACE 18:20:52.601] starbase_utils::fs  Opening file  file="C:\\Users\\wathhr\\.proto\\tools\\pnpm\\manifest.json"
[TRACE 18:20:52.601] starbase_utils::fs_lock  Unlocking file  file="C:\\Users\\wathhr\\.proto\\tools\\python\\manifest.json"
[TRACE 18:20:52.601] starbase_utils::fs  Opening file  file="C:\\Users\\wathhr\\.proto\\tools\\node\\manifest.json"
[TRACE 18:20:52.602] starbase_utils::fs_lock  Locking file  file="C:\\Users\\wathhr\\.proto\\tools\\pnpm\\manifest.json"
[TRACE 18:20:52.602] starbase_utils::fs_lock  Unlocking file  file="C:\\Users\\wathhr\\.proto\\tools\\pnpm\\manifest.json"
[TRACE 18:20:52.602] starbase_utils::fs_lock  Locking file  file="C:\\Users\\wathhr\\.proto\\tools\\node\\manifest.json"
[TRACE 18:20:52.603] starbase_utils::fs_lock  Unlocking file  file="C:\\Users\\wathhr\\.proto\\tools\\node\\manifest.json"
[TRACE 18:20:52.608] starbase::app  Running shutdown phase with 1 systems
Error: proto::tool::invalid_dir

  ×  inventory directory has been overridden but is not an absolute path. Only absolute paths are supported.

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
@wathhr Can you include the output from `proto debug config`?

**Comment by milesj** [comment]
Rust is the only tool with an override dir, but this looks absolute to me...

```
{"default_version":"stable","inventory":{"disable_progress_bars":true,"override_dir":"D:\Scoop\persist\rustup\.rustup/toolchains","version_suffix":"-x86_64-pc-windows-msvc"},"name":"Rust","plugin_version":"0.10.0","type":"Language"}
```

**Comment by wathhr** [comment]
> @wathhr Can you include the output from `proto debug config`?

~\.proto\.prototools
  node = "22.2.0"

~\.prototools
  [tools.node.aliases]
  node-lts = "20.13.1"

Configuration
  node = "22.2.0"

  [tools.node.aliases]
  node-lts = "20.13.1"

  [plugins]
  bun = "source:https://github.com/moonrepo/bun-plugin/releases/download/v0.12.0/bun_plugin.wasm"
  deno = "source:https://github.com/moonrepo/deno-plugin/releases/download/v0.11.0/deno_plugin.wasm"
  go = "source:https://github.com/moonrepo/go-plugin/releases/download/v0.11.1/go_plugin.wasm"
  internal-schema = "source:https://github.com/moonrepo/schema-plugin/releases/download/v0.12.0/schema_plugin.wasm"
  node = "source:https://github.com/moonrepo/node-plugin/releases/download/v0.11.0/node_plugin.wasm"
  npm = "source:https://github.com/moonrepo/node-plugin/releases/download/v0.11.0/node_depman_plugin.wasm"
  pnpm = "source:https://github.com/moonrepo/node-plugin/releases/download/v0.11.0/node_depman_plugin.wasm"
  python = "source:https://github.com/moonrepo/python-plugin/releases/download/v0.10.0/python_plugin.wasm"
  rust = "source:https://github.com/moonrepo/rust-plugin/releases/download/v0.10.0/rust_plugin.wasm"
  yarn = "source:https://github.com/moonrepo/node-plugin/releases/download/v0.11.0/node_depman_plugin.wasm"

  [settings]
  auto-clean = false
  auto-install = false
  detect-strategy = "first-available"
  telemetry = true

  [settings.http]
  allow-invalid-certs = false
  proxies = []

**Comment by wathhr** [comment]
> Rust is the only tool with an override dir, but this looks absolute to me...
> 
> ```
> {"default_version":"stable","inventory":{"disable_progress_bars":true,"override_dir":"D:\Scoop\persist\rustup\.rustup/toolchains","version_suffix":"-x86_64-pc-windows-msvc"},"name":"Rust","plugin_version":"0.10.0","type":"Language"}
> ```
> 
> Does that path exist on your machine? That value is coming from `RUSTUP_HOME`.

The `D:\Scoop\persist\rustup\.rustup/toolchains` directory does exist, it's from [scoop's rustup package](https://github.com/ScoopInstaller/Main/blob/47e6bc1d66965d0b7000348bdce494dfbfc8e481/bucket/rustup.json)
```
C:\Users\wathhr> ls %RUSTUP_HOME%
downloads  settings.toml  tmp  toolchains  update-hashes
```

**Comment by milesj** [comment]
Let me add more logging/debugging. It's still a bit hard to determine what exactly is causing the failure.

**Comment by milesj** [comment]
I think I maybe  found it. Hopefully this hotfix works: https://github.com/moonrepo/proto/pull/480

**Comment by milesj** [comment]
Can you try v0.35.3?

**Comment by wathhr** [comment]
v0.35.3 fixed the issue! Thanks for your help!

**Comment by milesj** [comment]
Awesome!
