### ISSUE TITLE
Plugin Removal Leaves Config Entries Intact

### ISSUE THREAD

**Issue by calmbino** [moonrepo/proto#481]
### What version?

0.35.3

### Which command?

proto plugin remove dotnet --global

### What happened?

I am currently testing the dotnet plugin using proto. Although the installation was successful, the dotnet CLI does not seem to work, so I want to remove the dotnet plugin.

I used the following command to remove the plugin:

```
proto plugin remove dotnet --global
```
However, the config content remains unchanged. Is this the expected behavior or a bug?

In my opinion, it should be completely removed.

### Trace logs?

![image](https://github.com/moonrepo/proto/assets/156172768/357db298-6ffe-4320-aaef-8a437c0213b4)

### Operating system?

Linux

### Architecture?

x64

**Comment by milesj** [comment]
That's a good question. That command was built to simply remove the plugin entry, but I can see how also removing the version makes sense too. Seams reasonable.

**Comment by calmbino** [comment]
> That's a good question. That command was built to simply remove the plugin entry, but I can see how also removing the version makes sense too. Seams reasonable.


I'm glad my curiosity has been satisfied! Thank you for the response :)

proto is a fantastic tool! Please keep up the great work with future updates"
