### ISSUE TITLE
Inhancement of node.js version detections

### ISSUE THREAD

**Issue by tolluset** [moonrepo/proto#483]
### What version?

0.35.3

### What happened?

When I install node modules packages, I met this message. 

```
Error: plugin::call_func::failed

  × unexpected character 'v' while parsing major version number 
```

The project using package.json for pin node version like this.

```
...

  "engines": {
    "node": ">=v18.0.0"
  }
```

The `v` makes incorrect. After I remove `v` works fine.

I think may support start with `v` node version would be more nice for compatibility to other tools?

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
This is reasonable, will look into.
