### ISSUE TITLE
missing_binary error when proto and proto-shim installed in /usr/bin

### ISSUE THREAD

**Issue by phnx47** [moonrepo/proto#490]
### What version?

0.35.4

### Which command?

proto install

### What happened?

I maintain [proto](https://aur.archlinux.org/packages/proto) for ArchLinux in AUR. I install binaries to `/usr/bin/proto` and `/usr/bin/proto-shim`. It worked before, but now I have this error:

```
Error: proto::shim::missing_binary
Unable to create shims as the proto-shim binary cannot be found.
Looked in the PROTO_HOME environment variable and ~/.proto/bin directory.
```

Can you look for binaries in global locations as well?

### Operating system?

Linux

### Architecture?

x64

**Comment by milesj** [comment]
@phnx47 We also support `PROTO_LOOKUP_DIR`, which is the location where `proto` and `proto-shim` exist.

**Comment by phnx47** [comment]
@milesj Has this been fixed or is this intended and the user should run `export PROTO_LOOKUP_DIR=/usr/bin`?

**Comment by milesj** [comment]
@phnx47 I'm not sure what the fix is here. proto needs to know where the shim binary is located if its not in `PROTO_HOME`.

I don't traverse `PATH` as there's no guarantee that the shim binary found, is actually the correct one, and not an outdated one.

**Comment by phnx47** [comment]
@milesj Ok, let's keep it as is. I will add a text instruction after installation that will explain what user should to do.

**Comment by milesj** [comment]
@phnx47 Can you talk about more about how the archlinux integration works? Is there docs?

**Comment by phnx47** [comment]
@milesj Not only archlinux, this more about linux. Binaries usually installed to `/usr/bin` and owned by `root`. Here is [Arch package guidelines](https://wiki.archlinux.org/title/Arch_package_guidelines) and [Rust package guidelines](https://wiki.archlinux.org/title/Rust_package_guidelines).

**Comment by milesj** [comment]
Thanks for this.

One thought I had, is use the currently running proto location (`/usr/bin/proto`), and locate the shim as a sibling (`/usr/bin/proto-shim`). Seems like it could work?

**Comment by milesj** [comment]
Maybe this https://github.com/moonrepo/proto/pull/497

**Comment by phnx47** [comment]
@milesj Nice, this issue is resolved! Thanks!

**Comment by milesj** [comment]
Nice! Let me know if there's issues with that approach.
