### ISSUE TITLE
Error: config::parse::failed Failed to parse ProtoConfig. plugins.moon: Unknown plugin scope `https`

### ISSUE THREAD

**Issue by dngrhm** [moonrepo/proto#520]
### What version?

0.37.0

### Which command?

moon run

### What happened?

This occurred after updating proto to 0.37.0

The command I'm running is moon but it looks like it is caused when proto is parsing the config.  It is reporting `https` as an unknown plugin scope.  I had to prepend  `source:` to all of the plugins in `.prototools` as a workaround.  I expected it to identify https and support it or give better feedback on how to fix the issue.

<img width="653" alt="image" src="https://github.com/moonrepo/proto/assets/1048802/fb05c876-0a37-4622-b77f-fb8efdecc8d9">

### Trace logs?

Error: config::parse::failed

  × Failed to parse ProtoConfig.
  ╰─▶   × plugins.act: Unknown plugin scope `https`.
         ╭─[2:7]
       1 │ [plugins]
       2 │ act = "https://raw.githubusercontent.com/theomessin/proto-toml-plugins/master/act.toml"
         ·       ────────────────────────────────────────┬────────────────────────────────────────
         ·                                               ╰── Fix this
       3 │ moon = "https://raw.githubusercontent.com/moonrepo/moon/master/proto-plugin.toml"
         ╰────

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
@dngrhm What moon version are you using? moon is coupled to a specific proto version behind the scenes, so I think you need to be using moon >= 1.25.2, or stay on an older proto version.

**Comment by dngrhm** [comment]
Thanks! Sry I missed your earlier comment.  Yes, that appears to be the case with the version mismatch.
