### ISSUE TITLE
Add `--include-global` support to `proto use`

### ISSUE THREAD

**Issue by milesj** [moonrepo/proto#533]
Right now `proto use` only installs tools from the current working directory and upwards, but does not include the global `~/.proto/prototools`. We should add an argument to also include global versions.

Work:
- Update https://github.com/moonrepo/proto/blob/master/crates/cli/src/commands/install_all.rs
- Add arguments
- Rework line 24 (refer to outdated for an example)

**Comment by varshith257** [comment]
@milesj I'd like to work on this issue
