### ISSUE TITLE
Dart language

### ISSUE THREAD

**Issue by itsezc** [moonrepo/proto#54]
Add support for the Dart language in Proto

**Comment by lalitkumawat1m** [comment]
want to contribute this project How can I start ?

**Comment by milesj** [comment]
@lalitkumawat1m 👋 

I think the first step is try to create a TOML plugin for dart: https://moonrepo.dev/docs/proto/plugins#creating-a-plugin

I should have WASM plugin support within the next few weeks, which will offer more control.

**Comment by milesj** [comment]
Now that WASM plugins are stable, this can be implemented in user land: https://moonrepo.dev/docs/proto/wasm-plugin
