### ISSUE TITLE
Shell activation workflow makes everything slow down?

### ISSUE THREAD

**Issue by asapo** [moonrepo/proto#544]
Hi, thanks for making a great tool.

But I noticed that shell activation workflow makes everything slow down.

I'm using zsh. So I followed the instructions.
https://moonrepo.dev/docs/proto/commands/activate#zsh

Then, I ran `echo "hello"`, it took over 200 ms.
When I removed shell activation, it only took about 20 ms.

That is a huge difference. 🥲

**Comment by milesj** [comment]
@asapo Does it happen every time? There will be an initial hit when you need to download the WASM plugins.

If you add `PROTO_LOG=trace` to your shell, you can see what's taking long.

**Comment by asapo** [comment]
> Does it happen every time?

Yes, it happens every time.

---

> If you add PROTO_LOG=trace to your shell, you can see what's taking long.

I'm not sure how can I read correctly but...

Small one:

```
[TRACE 10:57:12.534] starbase::app  Running shutdown phase
[DEBUG 2024-07-16 10:57:12.545] proto  Running proto v0.38.2  bin="proto" args=["activate", "zsh", "--export"] pid=29980
```

Another small one:

```
[DEBUG 10:57:12.547] proto_core::tool  Creating tool npm and instantiating plugin
[TRACE 10:57:12.562] warpgate::plugin  Created plugin container  id="go"
```

This one seems big:

```
[DEBUG 10:49:47.392] proto_core::tool  Located possible globals directories  tool="pnpm" dirs=["/Users/user/.local/share/pnpm", "/Users/user/Library/pnpm", "/Users/user/.proto/tools/node/globals/bin"]
[TRACE 10:49:47.523] proto_core::version_detector  Attempting to find version from .prototools files  tool="deno"
```

**Comment by milesj** [comment]
Making some changes here https://github.com/moonrepo/proto/pull/557

**Comment by milesj** [comment]
Made some improvements in v0.39, can you give it a shot?

**Comment by asapo** [comment]
Thank you!
I tried `proto 0.39.1` and it works faster as without proto. 🙌

**Comment by milesj** [comment]
Awesome!
