### ISSUE TITLE
Feature request: add proto to the scoop registry

### ISSUE THREAD

**Issue by W1M0R** [moonrepo/proto#548]
The [scoop package manager](https://scoop.sh/) offers a convenient way to install applications on Windows systems without requiring admin privileges.

If `proto` can be added to the scoop registry, then it could be [installed](https://scoop.sh/#/apps?q=proto) using:

```pwsh
scoop install proto
```

Some helpful guides and examples:

1. https://github.com/ScoopInstaller/Scoop?tab=readme-ov-file#what-sort-of-apps-can-scoop-install
2. https://github.com/ScoopInstaller/Scoop/wiki/Creating-an-app-manifest
3. https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests
4. https://github.com/ScoopInstaller/Main
5. https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets
6. https://github.com/ScoopInstaller/Main/blob/master/bucket/just.json
7. https://github.com/ScoopInstaller/Main/blob/master/bucket/go.json
8. https://github.com/ScoopInstaller/Main/blob/master/bucket/wasmer.json
9. https://github.com/ScoopInstaller/Main/blob/master/bucket/busybox.json

**Comment by W1M0R** [comment]
Here is a working the `proto.json` Scoop application manifest:

```json
{
  "version": "0.40.0",
  "description": "A pluggable multi-language version manager.",
  "homepage": "https://github.com/moonrepo/proto",
  "license": "MIT",
  "url": "https://github.com/moonrepo/proto/releases/download/v0.40.0/proto_cli-x86_64-pc-windows-msvc.zip",
  "hash": "af38f2c86813a4e7b70157bdb2478f8d9b5946e1435b795bb07cababe0d24ea9",
  "bin": [ "proto.exe", "proto-shim.exe" ],
  "checkver": {
    "github": "https://github.com/moonrepo/proto"
  },
  "autoupdate": {
    "url": "https://github.com/moonrepo/proto/releases/download/v$version/proto_cli-x86_64-pc-windows-msvc.zip"
  }
}

```

**Comment by milesj** [comment]
I don't plan to officially support other install methods outside what is already supported. This feels like something the community can maintain unofficially, in the same way that homebrew is.

**Comment by W1M0R** [comment]
@milesj All good, thanks.

**Comment by W1M0R** [comment]
Updated status.
