### ISSUE TITLE
Packages not found (cannot be excecuted)

### ISSUE THREAD

**Issue by RoyRao2333** [moonrepo/proto#567]
### What version?

0.39.2

### What happened?

Sorry for the fuzzy title... It's quicker to take a look at these screenshots:

---

For Node:

<img width="233" alt="image" src="https://github.com/user-attachments/assets/fa670c3b-e8c3-4424-b820-c1a1e46081b4">

But I can find `npm` and `corepack` in `~/.proto/tools/node/20.16.0/lib/node_modules`:

<img width="230" alt="image" src="https://github.com/user-attachments/assets/96d629f6-e366-4fb6-9d54-3da46e864195">

---

For Python, packages installed by pip cannot be found either:

```zsh
❯ which python
/Users/royrao/.proto/shims/python

❯ python --version
Python 3.12.4

❯ pip list cyberdrop-dl
Package              Version
-------------------- -----------
cyberdrop-dl         5.3.31

❯ cyberdrop-dl
zsh: command not found: cyberdrop-dl
```

I can only use it if I export `~/.proto/tools/python/3.12.4/install/bin` to PATH.

---

This is too much trouble. How can I fix this? Thanks!

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
@RoyRao2333 A few things:

- Node doesn't install npm. Just because npm is shipped with Node doesn't make it available in proto. You need to also install npm with proto.
- proto shims don't apply to _every_ binary that a tool has, just the primary one (and sometimes some secondary ones). This is especially true for packages. It's not possible to create a shim for every package binary.

With that said, if you want all of this to "just work", you need to use activation. https://moonrepo.dev/docs/proto/workflows Activation will only enable tools that have a version defined in a `.prototools` file.

**Comment by RoyRao2333** [comment]
@milesj 

Thanks for the reply.

And,

1. Can I safely delete npm and corepack folders in lib? (I'm a bit of a neat freak, sorry)
2. I read the doc and added the command to the end of my `.zshrc`:

```
# proto
export PROTO_HOME="$HOME/.proto";
export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PATH";
eval "$(proto activate zsh)"
# proto end
```

But still, I can't invoke `cyberdrop-dl` (already sourced `.zshrc`). Is there anything missing or am I getting this wrong? Please give some more specific guidance on how to use packages installed by pip?

Thank you very much for your time!

**Comment by RoyRao2333** [comment]
> Activation will only enable tools that have a version defined in a .prototools file.

I do have a `.prototools` file:

<img width="249" alt="image" src="https://github.com/user-attachments/assets/9fc08dba-9329-41f6-9421-ae9304d62b50">

But as far as I know, these versions are from the packages managed by proto, not by pip. Should I add package versions installed by pip? If do, how can I properly do that?

**Comment by RoyRao2333** [comment]
@milesj 

Thanks.

So as you can see, I've already appended `eval "$(proto activate zsh)"` to `.zshrc`. Why still not working?

**Comment by milesj** [comment]
Activation updates your `PATH` so all of these binaries are available. Globals are not enabled by default so you need to pass `--include-global`.

**Comment by RoyRao2333** [comment]
@milesj 

```
# .zshrc

# proto
export PROTO_HOME="$HOME/.proto";
export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PATH";
eval "$(proto activate zsh --include-global)"
# proto end
```

<img width="377" alt="image" src="https://github.com/user-attachments/assets/1e4e5cae-1414-415c-93ce-72ac8263a655">

I even reinstalled cyberdrop-dl and still no luck...

**Comment by milesj** [comment]
Are you reloading your shell after making changes to the config?

What's the output of `proto activate` if you run it manually?

**Comment by RoyRao2333** [comment]
@milesj 

Yes, I reload shell everytime.

Here's the output:

```zsh
❯ proto activate zsh --include-global
export __ORIG_PATH="$PATH"

_proto_hook() {
  trap '' SIGINT
  output=$(proto activate zsh --export)
  if [ -n "$output" ]; then
    eval "$output";
  fi
  trap - SIGINT
}
typeset -ag chpwd_functions
if (( ! ${chpwd_functions[(I)_proto_hook]} )); then
  chpwd_functions=(_proto_hook $chpwd_functions)
fi
```

**Comment by milesj** [comment]
Sorry, output of `proto activate --export`. It will show you the PATH being set.

You can also set `PROTO_LOG=trace` before activate to see what it's doing.

**Comment by RoyRao2333** [comment]
@milesj 

Here's the full output:

[PROTO_LOG=trace.txt](https://github.com/user-attachments/files/16424043/PROTO_LOG.trace.txt)

**Comment by milesj** [comment]
@RoyRao2333 I see `/Users/royrao/.proto/tools/python/3.12.4/install/bin` in your `PATH` because of activate. Be sure that you are installing pip packages using the proto version of pip. `which pip` should point to the python 3.12.4 version.

**Comment by RoyRao2333** [comment]
@milesj 

Yes, I'm sure that I'm using pip managed by proto. Here's the full output:

<img width="990" alt="image" src="https://github.com/user-attachments/assets/fc8fbc11-10a9-4c7c-bd7d-9ed655f0938f">

As you can see, `.proto/tools/python/3.12.4/install/bin` is not added to my PATH variable.

**Comment by milesj** [comment]
@RoyRao2333 Yeah something seems off. Let me dig through the code and see if I can find the bug.

**Comment by milesj** [comment]
I _think_ this will fix it. It's hard to verify some of this stuff. https://github.com/moonrepo/proto/pull/572

**Comment by milesj** [comment]
Can you try the latest patch?

If it still doesn't work, could you do the following:

1. Add `PROTO_LOG=trace` in your shell, before the activate command.
2. Add the eval + activate command snippet in your shell.
3. Open a new terminal (it should show some logs of activate triggering).
4. CD into a new directory (there should be more logs).
5. Verify `PATH`.

Then send over the logs :P

**Comment by RoyRao2333** [comment]
@milesj 

> 3. Open a new terminal
> 4. CD into a new directory
> 5. Verify PATH

Thanks, it's working after these steps in v0.39.4 :)

<img width="988" alt="image" src="https://github.com/user-attachments/assets/9dead9c1-5102-4e13-b1c5-6c28431ce41c">

Still got some questions here though:

1. Why must I change directories before this take effect? Wouldn't it be better to make it work once shell instance is initiated?
2. As you can see in the screenshot, `.proto/shims` and `.proto/bin` is duplicated because I added `"$PROTO_HOME/shims:$PROTO_HOME/bin"` to my PATH manually in my `.zshrc`. But If I don't do that, `proto` can't be found at all.

Thanks for you patience 😊

**Comment by milesj** [comment]
1. The hooks right now only fire on `cd`. The plan is to have it work when shell is activated, but it really depends on if there's a `.prototools` file and where a new terminal is opened in. There's also a few perf issues to work out. You could always call `_proto_hook` manually in your shell to trigger it for now. 
2. Activate includes the paths just in case. We can probably filter them if they already exist.

**Comment by RoyRao2333** [comment]
@milesj 

> We can probably filter them if they already exist

I'd like this very much!

> The plan is to have it work when shell is activated

I'll call `_proto_hook` for now. Hoping it'll work in the future releases.

Again, thanks for this excellent tool you guys brought us! Closing this issue now.

**Comment by milesj** [comment]
I was looking into removing the duplicate shims/bin paths, but it turns out it was added on purpose, and it's to ensure that proto shims take precedence over the injected tool bin directories.

If you don't care about that, you can pass `--no-shim` and `--no-bin` flags to the activate command.

**Comment by RoyRao2333** [comment]
@milesj 

Got it. Thanks!

I'll try `--no-shim` and `--no-bin` now.
