### ISSUE TITLE
Config modes not listed in --help

### ISSUE THREAD

**Issue by jakst** [moonrepo/proto#595]
### What version?

0.40.0

### Which command?

proto outdated --help

### What happened?

The new `proto outdated --config-mode=?` flag has replaced the `proto outdated --include-global` flag (showing a deprecation message when adding --include-global would be a nice touch), but the available modes are not listed when running `proto outdated --help`.

I know they're available in the changelog, but they should probably be listed in the help command as well.

See output
<img width="799" alt="image" src="https://github.com/user-attachments/assets/a2ea780a-4e4c-44f9-b22a-af5ec047b2ce">

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
Hrmm, I literally spent time making sure this worked... Will look into again.

**Comment by milesj** [comment]
Fixed
