### ISSUE TITLE
Regression in progress bar output

### ISSUE THREAD

**Issue by jakst** [moonrepo/proto#610]
### What version?

0.41.0

### Which command?

proto use

### What happened?

There has been a regression in the progress bar output. I believe it started happening after upgrading to v0.41.0, but not 100% sure.

The bars are now all over the place and the same tools are being repeated multiple times. This is what it looks like after `proto use --config-mode=global` has completed for me.

<img width="739" alt="image" src="https://github.com/user-attachments/assets/dd21f000-e0df-469b-b572-ccc02c07ca7b">

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
Hrmm, 0.41 was a pretty small release. I'll dig into the changes and see what's up.

**Comment by milesj** [comment]
Not seeing anything in the changes that would affect this. 

Do you remember what version you were on before? Does this happen if you restart the terminal?

**Comment by jakst** [comment]
I'm pretty sure I was on the latest version that was before that. But I ran it again a bit later and it did not look weird. So it might not be because something changed, but maybe because there were so many tools that updated? It's usually only one or two, and I have no issues. But this time all 8 tools upgraded at once.

**Comment by milesj** [comment]
@jakst Hrmm. Was your terminal window small by chance? I know it acts weird when there are more tools than available lines in the terminal.

**Comment by milesj** [comment]
Is this still happening?

**Comment by jakst** [comment]
Only experienced it that one time, so I think we can close for now.
