### ISSUE TITLE
installation of node14 failed , Error: net::not_found

### ISSUE THREAD

**Issue by panwenhua** [moonrepo/proto#611]
### What version?

0.41.0

### Which command?

proto use node 14

### What happened?

<img width="885" alt="image" src="https://github.com/user-attachments/assets/2137d37a-f29a-44d0-b0b0-962991e90313">

### Trace logs?

❯ proto use node 14 --log trace
[DEBUG 2024-09-10 16:46:17.757] proto  Running proto v0.41.0  bin="proto" args=["use", "node", "14", "--log", "trace"] pid=65024
[TRACE 16:46:17.762] starbase::app  Running startup phase 
[DEBUG 16:46:17.763] proto_core::proto  Creating proto environment, detecting store  store="/Users/panwenhua/.proto" home="/Users/panwenhua"
[TRACE 16:46:17.764] starbase::app  Running analyze phase 
[DEBUG 16:46:17.764] proto::systems  Loading configuration in upwards mode  working_dir="/Users/panwenhua/fe-project/hotel-fe-ebooking"
[DEBUG 16:46:17.764] proto_core::proto_config  Loading .prototools  file="/Users/panwenhua/.proto/.prototools"
[TRACE 16:46:17.764] starbase_utils::fs  Opening file  file="/Users/panwenhua/.proto/.prototools"
[TRACE 16:46:17.765] starbase_utils::fs_lock  Locking file  file="/Users/panwenhua/.proto/.prototools"
[TRACE 16:46:17.766] starbase_utils::fs_lock  Unlocking file  file="/Users/panwenhua/.proto/.prototools"
[TRACE 16:46:17.766] schematic::config::loader  Loading partial configuration  config="ProtoConfig"
[TRACE 16:46:17.766] schematic::config::loader  Creating layer from source  config="ProtoConfig" source="<code>"
[TRACE 16:46:17.766] schematic::config::loader  Merging partial layers into a final result  config="ProtoConfig"
[DEBUG 16:46:17.766] proto_core::proto_config  Merging loaded configs without global 
[DEBUG 16:46:17.766] proto_core::proto_config  Merged 0 configs 
[TRACE 16:46:17.766] starbase::app  Running execute phase 
[TRACE 16:46:17.768] starbase_utils::net  Checking for an internet connection  timeout=750
[DEBUG 16:46:17.768] proto::commands::install  Loading tool  id="node"
[DEBUG 16:46:17.768] proto_core::tool_loader  Finding a configured plugin  tool="node"
[DEBUG 16:46:17.768] proto_core::proto_config  Merging loaded configs with global 
[DEBUG 16:46:17.768] proto_core::proto_config  Merged 1 configs 
[DEBUG 16:46:17.768] proto_core::tool_loader  Using a built-in plugin  plugin="https://github.com/moonrepo/tools/releases/download/node_tool-v0.12.0/node_tool.wasm"
[TRACE 16:46:17.768] starbase_utils::net::offline  Resolving 1.1.1.1:53 
[TRACE 16:46:17.769] warpgate::loader  Creating plugin loader  cache_dir="/Users/panwenhua/.proto/plugins"
[TRACE 16:46:17.769] warpgate::loader  Loading plugin node  id="node" locator="https://github.com/moonrepo/tools/releases/download/node_tool-v0.12.0/node_tool.wasm"
[TRACE 16:46:17.769] starbase_utils::fs  Reading file metadata  file="/Users/panwenhua/.proto/plugins/node-dad1cbc99a433f56594101a3298836ae44edf6fc8b855aba481e8934e9c9215d.wasm"
[TRACE 16:46:17.769] warpgate::loader  Plugin already downloaded and cached  id="node" path="/Users/panwenhua/.proto/plugins/node-dad1cbc99a433f56594101a3298836ae44edf6fc8b855aba481e8934e9c9215d.wasm"
[DEBUG 16:46:17.769] proto_core::tool_loader  Loading WASM plugin  source="/Users/panwenhua/.proto/plugins/node-dad1cbc99a433f56594101a3298836ae44edf6fc8b855aba481e8934e9c9215d.wasm"
[TRACE 16:46:17.770] warpgate::plugin  Storing plugin identifier  id="node"
[TRACE 16:46:17.770] warpgate::plugin  Storing host environment  id="node" env={"arch":"arm64","libc":"gnu","os":"macos","home_dir":{"path":"/userhome/","virtual_prefix":"/userhome","real_prefix":"/Users/panwenhua"}}
[DEBUG 16:46:17.770] proto_core::tool  Creating tool node and instantiating plugin 
[DEBUG 16:46:17.770] warpgate::client  Creating HTTP client 
[DEBUG 16:46:17.948] warpgate::client  Created HTTP client 
[TRACE 16:46:17.948] warpgate::plugin  Creating plugin container  id="node"
[TRACE 16:46:17.957] warpgate::plugin  Created plugin container  id="node" plugin="efd970f6-66b8-4000-8fcf-139257306b7a"
[DEBUG 16:46:17.957] proto_core::tool  Created tool node and its WASM runtime 
[TRACE 16:46:17.957] warpgate::plugin  Calling guest function register_tool  id="node" plugin="efd970f6-66b8-4000-8fcf-139257306b7a" input={"id":"node"}
[TRACE 16:46:17.957] warpgate::plugin  Called guest function register_tool  id="node" plugin="efd970f6-66b8-4000-8fcf-139257306b7a" output={"config_schema":{"name":"NodePluginConfig","ty":{"type":"Struct","fields":{"bundled-npm":{"schema":{"ty":{"type":"Boolean"}},"hidden":false,"nullable":false,"optional":true,"read_only":false,"write_only":false},"dist-url":{"schema":{"ty":{"type":"String"}},"hidden":false,"nullable":false,"optional":true,"read_only":false,"write_only":false}},"partial":false}},"inventory":{},"name":"Node.js","plugin_version":"0.12.0","type":"Language"}
[DEBUG 16:46:17.957] proto_core::tool_manifest  Loading manifest.json  file="/Users/panwenhua/.proto/tools/node/manifest.json"
[TRACE 16:46:17.957] starbase_utils::fs  Opening file  file="/Users/panwenhua/.proto/tools/node/manifest.json"
[TRACE 16:46:17.957] starbase_utils::fs_lock  Locking file  file="/Users/panwenhua/.proto/tools/node/manifest.json"
[TRACE 16:46:17.958] starbase_utils::fs_lock  Unlocking file  file="/Users/panwenhua/.proto/tools/node/manifest.json"
 ──────────────────── | Installing Node.js                                                                                                                 [DEBUG 16:46:17.958] proto_core::flow::resolve  Resolving a semantic version or alias  tool="node" initial_version="~14"
[DEBUG 16:46:17.958] proto_core::flow::resolve  Loading available versions  tool="node"
[TRACE 16:46:18.521] starbase_utils::net::offline  Resolving 1.0.0.1:53 
[TRACE 16:46:18.722] starbase_utils::net  Online! 
[TRACE 16:46:18.722] starbase_utils::fs  Reading file  file="/Users/panwenhua/.proto/temp/.last-version-check"
[TRACE 16:46:18.722] warpgate::plugin  Calling guest function load_versions  id="node" plugin="efd970f6-66b8-4000-8fcf-139257306b7a" input={"initial":"~14"}
[TRACE 16:46:18.723] warpgate::host  Calling host function send_request  plugin="efd970f6-66b8-4000-8fcf-139257306b7a" input={"url":"https://nodejs.org/download/release/index.json"}
[TRACE 16:46:18.930] starbase::app  Running shutdown phase (because another phase failed) 
Error: plugin::call_func::failed

  × Failed to make HTTP request for https://nodejs.org/download/release/index.json.

### Operating system?

MacOS

### Architecture?

x64

**Comment by milesj** [comment]
@panwenhua I think nodejs.com was just down during this.

**Comment by y-anzai-colsis** [comment]
Command
proto install node 12.18.2

Result
Error: net::not_found

  × Unable to download file, the URL https://nodejs.org/download/release/v12.18.2/darwin-x64.tar.xz does not
  │ exist.

**Comment by milesj** [comment]
Hrmm, I don't think this changed in 0.41 but I'll take a look.

**Comment by milesj** [comment]
I believe I found the bug. It only applies to versions that don't support arm64. I'm guessing you're on M1 computers?

**Comment by y-anzai-colsis** [comment]
My PC is a Mac M1!!

**Comment by milesj** [comment]
Ok yeah, this should fix it: https://github.com/moonrepo/tools/pull/11

I'll publish a patch later today.

**Comment by y-anzai-colsis** [comment]
thank you! appreciate!!!

**Comment by milesj** [comment]
This should work now!

Do know that versions < 16 will use an x64 build, not arm64.

**Comment by y-anzai-colsis** [comment]
thank you! It worked fine in my environment! Thank you!
