### ISSUE TITLE
`"packageManager": "bun@1.1.27"` is ignored

### ISSUE THREAD

**Issue by baptisteArno** [moonrepo/proto#614]
### What version?

0.41.1

### What happened?

I'm expecting proto to automatically update bun as the current package.json state that it needs 1.1.27, I have 1.1.26 installed.

It works fine with pnpm but not bun for some reason?

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
@baptisteArno This field is for corepack and I don't think corepack supports bun?

**Comment by baptisteArno** [comment]
Indeed! https://github.com/nodejs/corepack/issues/295 My bad :)
