### ISSUE TITLE
proto activate shouldn't check for version when sourcing

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/proto#616]
### Which command?

proto activate fish | source

### What happened?

Sometimes new proto version is available is shown when opening the terminal.

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
We already don't check for a new version when running activate: https://github.com/moonrepo/proto/blob/master/crates/cli/src/session.rs#L33

Perhaps something else is running? Hard to tell without logs.

**Comment by milesj** [comment]
Closing this since it's not reproducable.
