### ISSUE TITLE
Best practice when download URLs of a tool changed

### ISSUE THREAD

**Issue by bjoern-reetz** [moonrepo/proto#617]
### What version?

any

### Which command?

proto install ruff

### What happened?

While I was using the proto 3rd party TOML plugin for ruff I realized it did not give me the latest version. Upon investigating I realized that the URLs to download the assets changed because the maintainers [dropped the "v" prefix in their git tags from version 0.5.0 on](https://github.com/astral-sh/ruff/tags?after=0.5.1).

I am not sure if proto TOML plugins support multiple URL schemes at the same time. Obviously I could write a new/seperate proto TOML plugin for ruff versions starting from 0.5.0. What is the best practice in this case?

### Operating system?

Linux

### Architecture?

x64

**Comment by milesj** [comment]
@bjoern-reetz Yeah TOML kind of assumes things are deterministic. The only option right now to support variation is to build a WASM plugin.

**Comment by bjoern-reetz** [comment]
Thank you for the clarification. While [I already managed to succesfully build a TOML plugin for Proto myself](https://github.com/bjoern-reetz/proto-plugins), I currently don't feel capable of building a WASM-based Ruff plugin.

I [talked to the maintainer of the original Ruff TOML plugin](https://github.com/Phault/proto-toml-plugins/issues/12) and he wished to keep his plugin backwards compatible. The only way I can see of making newer versions of Ruff available in Proto with TOML-based plugins is to build a new plugin while keeping the old one as-is.

I am aware that I could do this at any time without needing to bother you. I am mainly reaching out to you because off Ruffs plugin registry (both in [Proto's documentation](https://moonrepo.dev/docs/proto/tools) and via `proto plugin search ruff`).

Do you approve if I create a PR containing a replacement for the Ruff TOML plugin which only supports versions of [Ruff](https://github.com/astral-sh/ruff) >= 0.5.0?

**Comment by milesj** [comment]
@bjoern-reetz Yeah that seems fair. Maybe move the old ruff one into something like `ruff-0.4`?

**Comment by milesj** [comment]
Gonna close this since there's nothing actionable without adding a ton of overhead.
