### ISSUE TITLE
[Feature request] Support for bzip2 is missing from proto

### ISSUE THREAD

**Issue by shanipribadi** [moonrepo/proto#625]
### What version?

0.41.3

### Which command?

proto install

### What happened?

Trying to install https://github.com/xo/usql/releases/tag/v0.19.3
using proto succeed, but the binary can't be executed because actually it's never unpacked by proto.

This is due to missing support of bzip2 in starbase,_archive
https://github.com/moonrepo/starbase/blob/starbase_archive-v0.8.6/crates/archive/src/tar.rs

will have to add bzip2 support in starbase_archive first, and once that is released, can bump up the dependency in proto.

### Operating system?

Linux

### Architecture?

x64

**Comment by shanipribadi** [comment]
I've tested the updated starbase library on my local proto compilation by adding tar-bz2 features to starbase-archive and use Cargo patch feature to locally point the starbase dependencies.

(also did a cargo update to update the lock file)

**Comment by milesj** [comment]
Enabled in 0.41.4
