### ISSUE TITLE
It fails when I try to install node and pnpm at the same time

### ISSUE THREAD

**Issue by mio-19** [moonrepo/proto#639]
### What version?

0.41.7

### Which command?

proto install node pnpm

### What happened?

```
Error: proto::version::unresolved

  × Failed to resolve pnpm to a valid supported version for Node.js.
  help: Does this version exist and has it been released?
```

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
@mio-19 You can't install multiple tools like this, they would need to be separate commands: `proto install node && proto install pnpm`.

Or you can add the versions to `.prototools` and then run `proto install`.

**Comment by mio-19** [comment]
If this is the case, it would be helpful if the error message tell me that installing multiple tools like this is not supported

**Comment by milesj** [comment]
The second argument to `proto install` is the version, and in this case, "pnpm" is being treated as a version alias, like "latest" or "next". We have no way of intercepting the error message here.
