### ISSUE TITLE
How to deal with Python packages installed globally (pipx, poetry)?

### ISSUE THREAD

**Issue by kbzowski** [moonrepo/proto#644]
### What version?

0.41.7

### What happened?

I tested experimental support for python and it looks great. But I am wondering how to proceed with tasks like installing `pipx` or `poetry`? pip is available so I tried: `pip install pipx` and `python -m pip install --user pipx` but in both cases pipx was not added to PATH. 

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
@kbzowski You would need to use `proto activate` to make them available.

Only tools/plugins within proto itself get added to PATH, but those are basically global packages not part of proto.

**Comment by kbzowski** [comment]
Thank you for explanation. I migrated from volta and it was not so obvious.
