### ISSUE TITLE
Feature request: Configure environment variables from .env file

### ISSUE THREAD

**Issue by six5536** [moonrepo/proto#645]
### What version?

0.23.0

### Which command?

proto

### What happened?

It would be great to be able to specify a file from the .prototools file from which to load environment variables.
mise does this with something like:

```
[env]
_.file = '.env'
```

Our specific use-case: 
Embedded C toolchain can be installed in any folder by a developer. Each dev has their own .env file for the project which specifies the location of the toolchain.

BTW Great project, I long for the day when this type of tool is mature.

### Operating system?

MacOS

### Architecture?

x64

**Comment by milesj** [comment]
Yeah this seems reasonable. Let me look into it.

**Comment by milesj** [comment]
Added in v0.43
