### ISSUE TITLE
Installing via powershell completely clears the previous $profile content

### ISSUE THREAD

**Issue by iSplasher** [moonrepo/proto#648]
### What version?

0.41.7

### Which command?

irm https://moonrepo.dev/install/proto.ps1 | iex

### What happened?

When installing proto with Powershell 7, it updates the chosen profile by **clearing the previous content** instead of appending to it, so you end up with a profile that only contains
```powershell

# proto
$env:PROTO_HOME = Join-Path $HOME ".proto";
$env:PATH = @(
  (Join-Path $env:PROTO_HOME "shims")
  (Join-Path $env:PROTO_HOME "bin")
  $env:PATH
) -join [IO.PATH]::PathSeparator;
```

I completely lost my hard-crafted PS profile :I

### Operating system?

Windows

### Architecture?

x64

**Comment by milesj** [comment]
We definitely append: https://github.com/moonrepo/proto/blob/master/crates/cli/src/shell.rs#L64

It's hard to say whether this was proto or not without logs.

**Comment by iSplasher** [comment]
This was my own fault, sorry.
