### ISSUE TITLE
Proto version with protoc v3.20.3 

### ISSUE THREAD

**Issue by Tanakpek** [moonrepo/proto#651]
### What version?

0.42.

### What happened?

Hey guys, so we've used the protoc npm package to generate typescript clients however proto (this one) seems to be ahead of that npm package. namely that one generates 3.20.3 clients whereas with version 0.42, im generating  5.28.3. Which version of proto from brew should I install to get a version of proto that generates 3.20.3 clients using protoc

### Operating system?

Mac

### Architecture?

ARM

**Comment by milesj** [comment]
This project isn't related to `protoc` or protobuf.

But to answer your question, you probably want `brew install protobuf`, not `brew install proto`.
