### ISSUE TITLE
Feature request: Add netrc authentication for reqwest library

### ISSUE THREAD

**Issue by harlequin** [moonrepo/proto#652]
### What version?

latest

### Which command?

proto

### What happened?

It would be create the the download builder will be extended by the [rust-netrc](https://crates.io/crates/reqwest-middleware) crate, which is compatible with the reqwest-middleware.
This would introduce the ability to access protected resources via the .netrc file (host, login, password).

### Operating system?

Linux

### Architecture?

x64

**Comment by milesj** [comment]
This would only work if the proto commands are ran in the directory that contains `.netrc` right?

**Comment by harlequin** [comment]
No, .netrc is a file which is stored inside HOME directory. The library reads it automaticlly from this Location.

**Comment by milesj** [comment]
Ok that seems reasonable enough. Can look into.

**Comment by milesj** [comment]
Added in v0.43
