### ISSUE TITLE
The most preferred profile file comes last in setup

### ISSUE THREAD

**Issue by tats-u** [moonrepo/proto#655]
### What version?

0.42.1

### Which command?

proto  setup

### What happened?

RHEL / Fedora (.bash_profile exists)

![image](https://github.com/user-attachments/assets/e2a11c9c-1515-46dd-bb5c-eaeeb2b94212)

`.profile` here doesn't have an effect. (https://github.com/moonrepo/starbase/pull/105)
`.bash_profile` should come first.

Ubuntu (only .profile exists)

![image](https://github.com/user-attachments/assets/e2a11c9c-1515-46dd-bb5c-eaeeb2b94212)

`.bashrc` is not a profile. `.profile` should come first.

I believe the following code is wrong:

https://github.com/moonrepo/proto/blob/9f47f9d60c9d7f74b38bfc96ced8be1e012422fb/crates/cli/src/shell.rs#L32

> Check in reverse order as the most common profile is always last in the list

https://github.com/moonrepo/proto/blob/9f47f9d60c9d7f74b38bfc96ced8be1e012422fb/crates/cli/src/shell.rs#L128-L133

The return value of `get_profile_paths` in some shells is the opposite. (but not always so)

- https://github.com/moonrepo/starbase/issues/108

### Operating system?

Linux

### Architecture?

x64

**Comment by milesj** [comment]
Fixed in v0.43
