### ISSUE TITLE
May support for the shell `/bin/sh` ?

### ISSUE THREAD

**Issue by microJ** [moonrepo/proto#672]
### What happened?

My Enviroment:
- macOS
- fish
- xcode
- nodejs (installed with proto)

it happens error when xcode building script shell, show `[Error] Could not find node.`. The reason is xcode use `/bin/sh` run shell script. 
When I run `proto activate sh` in fish shell, show Error:
```
Error: shell::no_hook_support

  × Your shell, sh, does not support "on change directory" hooks. Please remove the command from your
  │ shell that is triggering this hook.
```

But I find `/Users/j/.proto/shims` & `/Users/j/.proto/bin` in sh shell `env.PATH`.

May support sh shell ?

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
@microJ Since `sh` doesn't support activation hooks, what are you using `proto activate` for exactly? Just to inject the shim/bin paths?

**Comment by microJ** [comment]
@milesj yes, `Xcode` run scripts with  sh. But I can add shims/bin to  `$PATH` to resolve
