### ISSUE TITLE
Corepack not installed with Node

### ISSUE THREAD

**Issue by QuiiBz** [moonrepo/proto#84]
I've tried to switch to proto to manage my tools, but it seems like [Corepack](https://nodejs.org/docs/latest-v18.x/api/corepack.html) isn't installed when installing Node. Is that an expected behavior?

**Comment by milesj** [comment]
@QuiiBz This is by design. proto does everything corepack does and more. What's your use case for corepack?

**Comment by QuiiBz** [comment]
I would like to run `yarn`, `pnpm`... without prefixing my commands with `proto run`. I could add an alias in my shell configuration, but I do like the experience of Corepack where you only have to run `corepack enable` and then it automatically downloads and picks the correct version of the package manager you're running.

**Comment by milesj** [comment]
@QuiiBz You don't need to run tools via `proto run`. Just add `~/.proto/bin` to your path and `npm`, `node`, etc will work.

**Comment by QuiiBz** [comment]
Am I missing something in the documentation, or it's not possible to replicate what corepack does? I want versioning on `pnpm`, `yarn` & `npm` based on the `packageManager` field of the current directory.

I already have `~/.proto/bin`, but `pnpm` / `yarn` aren't in the path.

**Comment by QuiiBz** [comment]
I think I've figured it out: I first have to install a version of `pnpm` / `yarn` using proto, and set `auto-install: true` in `~/.proto/config.toml` to replicate what corepack does.

**Comment by milesj** [comment]
Yeah you'll need `auto-install` for this, or use `.prototools` + `proto use`. I can probably update `proto use` to also take into account the `packageManager` field.

**Comment by QuiiBz** [comment]
That would be great. Thanks for your help!
