### ISSUE TITLE
`proto clean`: "" is not a built-in tool and has not been configured as a plugin

### ISSUE THREAD

**Issue by QuiiBz** [moonrepo/proto#92]
Running `proto clean`, I get this error where the plugin name seems to be empty:

![Screenshot 2023-04-28 at 14 39 55](https://user-images.githubusercontent.com/43268759/235149797-16231a5e-ea3d-4a89-9f77-43e225e389e0.png)

I'll dig more into the code soon to try to fix the issue.

**Comment by milesj** [comment]
Easy enough fix.
