### ISSUE TITLE
Proto and all installed tools break after `proto upgrade`

### ISSUE THREAD

**Issue by jakst** [moonrepo/proto#93]
Whenever a new version of proto arrives and I run `proto upgrade`, the whole installation breaks. I can't run proto or any of the tools installed by proto. Installation only breaks if there's actually a new version available. The only way to resolve the issue is to run the installation script again.

Examples of broken output
```
proto --help
[1]    33324 killed     proto --help
```

```
pnpm run dev
[1]    33165 killed     pnpm run dev
```

I initially installed proto with `curl -fsSL https://moonrepo.dev/install/proto.sh | bash`,  and that's also what I use to fix proto when it breaks.

I'm running MacOS v13.3.1 on a 16" MacbookPro M1 Max.

**Comment by milesj** [comment]
This is... odd. I'm basically running the same specs as you and have no issue. 

My initial thought is that this is a permissions problem. If you could verify what the perms are before an upgrade, and again after, to see if there's any differences, that would be helpful.

**Comment by jakst** [comment]
I'll try to remember to check this when I notice a new version is available next time! Any specific files I should check the permissions for?

**Comment by milesj** [comment]
@jakst It's just the file at `~/.proto/bin/proto`.

**Comment by milesj** [comment]
I just released 0.8.1 if you want to try it with that.

**Comment by jakst** [comment]
No changes in permissions as far as I can tell
<img width="851" alt="image" src="https://user-images.githubusercontent.com/3687893/235594247-b6adff30-9ddb-4fbe-9579-41a2dba4bceb.png">

**Comment by milesj** [comment]
Well that's unfortunate. This also matches what I have locally 🤔

**Comment by milesj** [comment]
Next time can you try with `PROTO_LOG=trace` and maybe it'll reveal something.

**Comment by jakst** [comment]
Will do!

**Comment by jakst** [comment]
Btw @milesj, is there any way to install an older version of proto so I can iterate a bit faster on retrying?

**Comment by milesj** [comment]
The install script supports aversion argument, but I'm not 100% on the syntax. Maybe:

```
curl -fsSL https://moonrepo.dev/install/proto.sh | bash "1.2.3"
```

**Comment by jakst** [comment]
That wasn't the syntax 😅 But I downloaded the script and ran it with an old version. Unfortunately, I don't get any error when I downgrade and upgrade again. I'll wait for the next release and try with logging enabled then

**Comment by milesj** [comment]
Well that's even weirder, hah

**Comment by jakst** [comment]
No luck with the `PROTO_LOG=trace` variable 😕

<img width="774" alt="image" src="https://github.com/moonrepo/proto/assets/3687893/80f6fdc7-8814-4b0b-8056-7f35e23631c9">

**Comment by milesj** [comment]
So I've ran into this myself, and it always happens when I have the older version of proto running in the background.

For example, running the website dev server via proto. Once I quite the server, the "proto killed" stops and it shows the new version.

Can you verify that's the case for you also?

**Comment by jakst** [comment]
> So I've ran into this myself, and it always happens when I have the older version of proto running in the background.
> 
> For example, running the website dev server via proto. Once I quite the server, the "proto killed" stops and it shows the new version.
> 
> Can you verify that's the case for you also?

Oh, nice find!
I'll take note whether any processes are running before upgrading next time and try to close them first.

**Comment by jakst** [comment]
Tried closing all running node processes before upgrading to v0.9.1, and it worked like a charm.

Has this helped you narrow down the root cause?

**Comment by milesj** [comment]
Nice, at least I know what the problem is. I'll take a look at how other libs do self updating and avoid this problem.

**Comment by jakst** [comment]
Upgraded v0.9.2 to v0.10.0 today with a node dev-server running without issues. I think we can consider this resolved! 🎉  

Thank you!

**Comment by milesj** [comment]
Awesome, lucky guess that worked!
