### ISSUE TITLE
`npm start` is broken when using proto-installed npm 

### ISSUE THREAD

**Issue by bjesuiter** [moonrepo/proto#99]
I have npm installed via proto. 

When I'm inside a repo which has no .prototools file, 
I'd expect `npm start` to simply execute the start script. 

However, it seems not to work, I throws this error: 

```
Error: proto::alias::unknown

  × Version alias bundled could not be found in the manifest.
```

I'm completely lost on what that means, seems like an internal error to me. 
I also don't know, which infos you need to debug this, please ask if you need something more specific. 

OS: MacOS Ventura (13.3) 
Proto Version:  0.8.2 (but seemed to have happened also with 0.8.1)

**Comment by milesj** [comment]
@bjesuiter Interesting error. Did you recently install proto, or have you had it installed from an early version, like 0.3?

**Comment by bjesuiter** [comment]
Hmm, it may be that I installed it in version 0.3 or something, I was very early after the announcement. But I upgraded to 0.8.1 recently and to 0.8.2 shortly after

**Comment by milesj** [comment]
My current thought is that you installed proto before this bundling stuff was added, so then you were in a weird state were it wasn't installed correctly.

**Comment by bjesuiter** [comment]
Maybe this is the case. Since It works now, I'll close the issue :)
